### ISSUE TITLE
problem while writing a note (at the end and after the visible writing area)

### ISSUE THREAD

**Issue by franco27** [clipto-pro/Desktop#10]
version 1.2.0 - windows 10 x64

When I write a note and I'm at the end of the editing window, so at the very bottom, I can continue writing but the cursor hides and I always come back up (the last written texts are no longer visible).
The Clipto window is not in full screen. (it is resized)

1/ CTRL+3  for the display mode
2/ I write a new note, on the visible writing area, there is no problem
3/ when I get to the end of the visible writing area, when I'm still writing, there's the window that goes up hiding the last line
4/ When I go down, I start writing again and I always come back up.
5/ I am obliged to enlarge the window otherwise I do not see what I write

on the screenshot, if I write below the red line, it goes up all the time 
![2019-09-08_18h27_31](https://user-images.githubusercontent.com/31793920/64491526-e2cd1180-d269-11e9-99f9-a0d080032197.png)

**Comment by atrashler** [comment]
you have found a bug:)

**Comment by atrashler** [comment]
Please check how it works on Web v1.2.1 (https://clipto.pro/#/editor) now (preferred browser - Chrome). Later we will include the similar fix in Desktop apps.

**Comment by atrashler** [comment]
> version 1.2.0 - windows 10 x64
> 
> When I write a note and I'm at the end of the editing window, so at the very bottom, I can continue writing but the cursor hides and I always come back up (the last written texts are no longer visible).
> The Clipto window is not in full screen. (it is resized)
> 
> 1/ CTRL+3 for the display mode
> 2/ I write a new note, on the visible writing area, there is no problem
> 3/ when I get to the end of the visible writing area, when I'm still writing, there's the window that goes up hiding the last line
> 4/ When I go down, I start writing again and I always come back up.
> 5/ I am obliged to enlarge the window otherwise I do not see what I write
> 
> on the screenshot, if I write below the red line, it goes up all the time
> ![2019-09-08_18h27_31](https://user-images.githubusercontent.com/31793920/64491526-e2cd1180-d269-11e9-99f9-a0d080032197.png)
Please check how it works on Web v1.2.1 (https://clipto.pro/#/editor) now (preferred browser - Chrome). Later we will include the similar fix in Desktop apps.

**Comment by atrashler** [comment]
v1.3.0
