### ISSUE TITLE
Always show slider line 

### ISSUE THREAD

**Issue by klorinczi** [clipto-pro/Desktop#101]
Could be possible to always show the slider line?

Current behavior of the slider is strange.

**Comment by atrashler** [comment]
> Could be possible to always show the slider line?
> 
> Current behavior of the slider is strange.

Which slider? Screenshot is welcome

**Comment by klorinczi** [comment]
I mean the slider at right side, which is hidden after a few seconds. 

I would like to see the slider bar, without hiding it.
I miss it on Windows and Android, too.

Currently I can not create screenshot.

**Comment by atrashler** [comment]
> I mean the slider at right side, which is hidden after a few seconds.
> 
> I would like to see the slider bar, without hiding it.
> I miss it on Windows and Android, too.
> 
> Currently I can not create screenshot.

Got it. No need a screenshot.

On Android it is not implemented yet.
On Desktop I can change this behavior remotely (make it longer or shorter or display always). You really need to show these sliders always? Usuallly it appears when you scroll the context and want do it faster. So you see the slider for several seconds that should be enough to find it and use.

**Comment by klorinczi** [comment]
Yes, I feel it is needed. 

I miss it on Android.

On Desktop, often I get the vertical divider resize mouse feature, instead of vertical scrolling.

This happens because the scrolling bar is not visible, and no visual point where to locate the mouse.

So the vertical scrollbar background should be a bit different from the window background. Might be optionally changed.

**Comment by atrashler** [comment]
Actually this issue should already be fixed several version ago. But lets link it with the latest update 7.2.17
