### ISSUE TITLE
Clipto (5.1.1) does not work correctly on macOS Hig Sierra (10.13.6)

### ISSUE THREAD

**Issue by NY-Mentor** [clipto-pro/Desktop#103]
Version 5.1.1 does not detect the automatic copy from clipboard function until after several minutes or even fails to register it.
It works correctly by disabling the Notes from Clipboard option on the menu and then manually using the Save from Clipboard function.
I had to revert to 5.0.3 which works without problems.

Greetings.

**Yuan**

**Comment by atrashler** [comment]
> Version 5.1.1 does not detect the automatic copy from clipboard function until after several minutes or even fails to register it.
> It works correctly by disabling the Notes from Clipboard option on the menu and then manually using the Save from Clipboard function.
> I had to revert to 5.0.3 which works without problems.
> 
> Greetings.
> 
> **Yuan**

Thanks for letting me know! I will disable the experimental feature that is the cause of this problem.
