### ISSUE TITLE
Clipto 5.1.1  shows that newer version 5.0.3 is available , weird !

### ISSUE THREAD

**Issue by jackycms** [clipto-pro/Desktop#104]
i am using  Clipto (5.1.1)  but a popup shows that a newer version is available (5.0.3)

![image](https://user-images.githubusercontent.com/2857427/118895740-54af9680-b939-11eb-836a-02af67d62680.png)

**Comment by atrashler** [comment]
It is because I have temporary unpublished the version 5.1.1 due to its unstable behavior. The new version 5.1.2 will be published soon.
