### ISSUE TITLE
Universal Clipboard to copy content notifications, can allow to close

### ISSUE THREAD

**Issue by Vstory** [clipto-pro/Desktop#11]

**Comment by atrashler** [comment]
Could you write the platform where the issue is reproducible?

**Comment by atrashler** [comment]
> No description provided.

Could you write the platform where the issue is reproducible?

**Comment by atrashler** [comment]
> > No description provided.
> 
> Could you write the platform where the issue is reproducible?

Could you confirm that the notification can not be closed by clicking on it? Current implementation should allow to click on a notification to close it.

**Comment by roamerhappiness** [comment]
What does he mean by this exactly? Not sure I understand what he means by this issue?

**Comment by Vstory** [comment]
> > > No description provided.
> > 
> > 
> > Could you write the platform where the issue is reproducible?
> 
> Could you confirm that the notification can not be closed by clicking on it? Current implementation should allow to click on a notification to close it.


Sorry, reply so late.
After the mobile device copies the text, the PC will have a notification.Can you provide a close notification button?

**Comment by atrashler** [comment]
> > > > No description provided.
> > > 
> > > 
> > > Could you write the platform where the issue is reproducible?
> > 
> > 
> > Could you confirm that the notification can not be closed by clicking on it? Current implementation should allow to click on a notification to close it.
> 
> Sorry, reply so late.
> After the mobile device copies the text, the PC will have a notification.Can you provide a close notification button?

By current logic it is possible to click on such notification and it will be closed. Does it work in such way or you want to see some other behaviour with separate action button?

**Comment by atrashler** [comment]
> What does he mean by this exactly? Not sure I understand what he means by this issue?

need to ask more questions to make it clear

**Comment by Vstory** [comment]
> > > > > No description provided.
> > > > 
> > > > 
> > > > Could you write the platform where the issue is reproducible?
> > > 
> > > 
> > > Could you confirm that the notification can not be closed by clicking on it? Current implementation should allow to click on a notification to close it.
> > 
> > 
> > Sorry, reply so late.
> > After the mobile device copies the text, the PC will have a notification.Can you provide a close notification button?
> 
> By current logic it is possible to click on such notification and it will be closed. Does it work in such way or you want to see some other behaviour with separate action button?


Thank you. Let me give it a try.
I am troubled by the constant sending of notifications.

**Comment by Vstory** [comment]
I found it. You need to right-click on the notification in the task center to close it.

**Comment by roamerhappiness** [comment]
If you open the Windows notification screen you can right click and there is and option to disable the notifications.

**Comment by Vstory** [comment]
> If you open the Windows notification window, you can right click on the Clipto notification and there is an option to disable the notifications.


Yes. Thank you

**Comment by GitAlexToTheGreek** [comment]
Hi everyone 🙂
@atrashler 

Somewhat related... 

I *would* like to see notification "banners" on the desktop (running ClipTo v2.8.1 on Windows 10) every time I copy something on mobile, but don't wish to see CT notifications in the Action Center. 

Like @Vstory mentioned...
> I found it. You need to right-click on the notification in the task center to close it.

I clicked on the small settings icon to disable just the Action Center notifications, but ended up disabling all desktop notifications for CT (don't recall what I clicked). 

In Windows, when I go to Settings/System/Notifications & actions, then scroll down to "Get Notifications from these senders", ClipTo isn't listed, and there's no way to add applications. So re-enabling the banner notifications that way won't work... 

Does it have to be done via the registry? 
Or simply reinstall CT to restore defaults? 

Worth mentioning, the universal clipboard syncing between phone & computer works instantaneously regardless of the lack of notifications, so no issues there. Regarding current ClipTo settings: Sync Notes, Notes from Clipboard and Universal Clipboard are all enabled.

Can anyone advise?

**Comment by atrashler** [comment]
Try to re-install the app:) But I am not sure will it help or not (I an testing this functionality only on macOS)

**Comment by GitAlexToTheGreek** [comment]
> Try to re-install the app:) But I am not sure will it help or not (I an testing this functionality only on macOS)

Hey [Alex](https://github.com/atrashler),

Did a reinstall but still no notifications showing.

I suppose I could contact Microsoft...

Let me know if you have any further suggestions.

**Comment by GitAlexToTheGreek** [comment]
Potentially found something relevant in the registry but would like your feedback before attempting to edit... 

<img width="759" alt="1" src="https://user-images.githubusercontent.com/59787873/85522035-fc9dd200-b5b9-11ea-8d5b-843ecc1855b1.png">

<img width="540" alt="2" src="https://user-images.githubusercontent.com/59787873/85522186-2951e980-b5ba-11ea-8244-211f30683a1b.png">

<img width="414" alt="3" src="https://user-images.githubusercontent.com/59787873/85522235-38389c00-b5ba-11ea-8003-51161f5dbd3c.png">

Do you think changing the value from 0 to will 'wake up' the universal clipboard notifications again?
What about altogether deleting the entry? Would that possibly reset those notification defaults? 

@atrashler

**Comment by atrashler** [comment]
I can not help you in this question, sorry. I do not know the specific of Windows based systems:)
But if you find an answer on it - let me know, so I can help others if anyone else will experience the same problem.

**Comment by GitAlexToTheGreek** [comment]
Hey,

So it wasn't possible to restore the original notifications via the registry either and ended up reinstalling Windows.

**Comment by atrashler** [comment]
Seems like it is better to add a setting in the app to control this notification. Have added to the backlog. Thanks!

**Comment by GitAlexToTheGreek** [comment]
> Seems like it is better to add a setting in the app to control this notification. Have added to the backlog. Thanks!

Much appreciated.

**Comment by atrashler** [comment]
In this version (https://github.com/clipto-pro/Desktop/releases/tag/v3.1.0) I have added a possible fix that should display Clipto in the system notification settings and let to configure its behaviour. Please check it. At least in works on my VirtualBox Windows image:)
