### ISSUE TITLE
Red line when writing  in my native language

### ISSUE THREAD

**Issue by solisoares** [clipto-pro/Desktop#110]
Hi, first of all I want to say that I am loving this Project. It keeps things very well organized!

Second thing is that I am having a problem when writing in my native language, Brazilian Portuguese. **Even though I have changed the app language to mine.**

The issue is that the app does not recognize my language and keeps throwing a red line under the words I type. Unless I write in English, which is weird, since as I said, already have changed the app language to Brazilian Portuguese.

I am using Kubuntu version 20.04 LTS and Clipto 5.1.2 (installed with `sudo snap install clipto`)

Bellow there is a screenshot as an example:
![Screenshot_20210628_161722](https://user-images.githubusercontent.com/77312190/123692022-b3b3d580-d82c-11eb-9e43-68f994a83028.png)

And as I said it, the app language:
![Screenshot_20210628_162450](https://user-images.githubusercontent.com/77312190/123692893-bb27ae80-d82d-11eb-9c2a-d4c496e9b2f3.png)

Can you guys help me? 
Thanks a lot!

**Comment by atrashler** [comment]
should be fixed in 7.2.0
