### ISSUE TITLE
Clipboard not syncing

### ISSUE THREAD

**Issue by yochananmarqos** [clipto-pro/Desktop#115]
My account syncs 600 notes and the clipboard limit is 300. Instead of purging the old clipboard notes, it stops syncing the new notes. I tried signing out and signing back in. 

Desktop:
Manjaro GNOME
`clipto-bin` 5.1.2-1 ([AUR](https://aur.archlinux.org/packages/clipto-bin))

Mobile:
T-Mobile OnePlus 7 Pro
Oxygen OS 11.0.1.3
Android 11
Clipto 6.0.16

**Comment by atrashler** [comment]
> My account syncs 600 notes and the clipboard limit is 300. Instead of purging the old clipboard notes, it stops syncing the new notes. I tried signing out and signing back in.
> 
> Desktop:
> Manjaro GNOME
> `clipto-bin` 5.1.2-1 ([AUR](https://aur.archlinux.org/packages/clipto-bin))
> 
> Mobile:
> T-Mobile OnePlus 7 Pro
> Oxygen OS 11.0.1.3
> Android 11
> Clipto 6.0.16

the questions:

1) do you use the app with internet constantly or it syncs your data later when the internet is available
2) do you use the clipboard monitoring only on one device or more than one.
3) the issue relates to the desktop or android (sent from Android, but reported for Desktop).

Actually it is a known issue and I will fix it in the upcoming Desktop release. But the answers on mentioned questions could help me better test the fix.
Thanks!

**Comment by yochananmarqos** [comment]
1. Yes, always on the internet
2. One Android phone and two laptops, both running Manjaro.
3. The clipboard seems to stop syncing on the desktop version. It's intermittent sometimes.

**Comment by atrashler** [comment]
should be fixed in 7.2.0
