### ISSUE TITLE
BUG. App is not auto starting in Windows 10

### ISSUE THREAD

**Issue by ShobanChiddarth** [clipto-pro/Desktop#116]
![image](https://user-images.githubusercontent.com/68191453/128522564-b937f9a8-d7a7-4967-8057-8bf0c649df2c.png)
I enabled auto start but still, I have to open this app from the Start menu every time for it to work. I cant even find this app in 'Startup settings'
![image](https://user-images.githubusercontent.com/68191453/128522787-43d25326-23aa-4b06-a0b1-40cba1106e98.png)

**Comment by atrashler** [comment]
> ![image](https://user-images.githubusercontent.com/68191453/128522564-b937f9a8-d7a7-4967-8057-8bf0c649df2c.png)
> I enabled auto start but still, I have to open this app from the Start menu every time for it to work. I cant even find this app in 'Startup settings'
> ![image](https://user-images.githubusercontent.com/68191453/128522787-43d25326-23aa-4b06-a0b1-40cba1106e98.png)

The issue relates to the binary (exe) downloaded from Github or from the Windows Market?

**Comment by ShobanChiddarth** [comment]
Downloaded from the site clipto.pro

**Comment by atrashler** [comment]
should be fixed in v7.2.7
