### ISSUE TITLE
[Linux] Cannot copy & paste files

### ISSUE THREAD

**Issue by yochananmarqos** [clipto-pro/Desktop#117]
If I copy a file in Nautilus, Clipto copies the path to the clipboard. A few seconds later, I'm not able to paste and the Paste context menu item is greyed out. If I copy the same file again, I can paste it. If I exit Clipto, everything works as expected.

Desktop:
Manjaro GNOME
`clipto-bin` 5.1.2-1 ([AUR](https://aur.archlinux.org/packages/clipto-bin))

Mobile:
T-Mobile OnePlus 7 Pro
Oxygen OS 11.0.1.3
Android 11
Clipto 7.1.1-release

**Comment by atrashler** [comment]
> If I copy a file in Nautilus, Clipto copies the path to the clipboard. A few seconds later, I'm not able to paste and the Paste context menu item is greyed out. If I copy the same file again, I can paste it. If I exit Clipto, everything works as expected.
> 
> Desktop:
> Manjaro GNOME
> `clipto-bin` 5.1.2-1 ([AUR](https://aur.archlinux.org/packages/clipto-bin))
> 
> Mobile:
> T-Mobile OnePlus 7 Pro
> Oxygen OS 11.0.1.3
> Android 11
> Clipto 7.1.1-release

Nautilus is an app? could you send a link on it?

**Comment by yochananmarqos** [comment]
Nautilus is the default file manager on GNOME, aka [Files](https://wiki.gnome.org/Apps/Files).

**Comment by atrashler** [comment]
> Nautilus is the default file manager on GNOME, aka [Files](https://wiki.gnome.org/Apps/Files).

Got it:) Was confused by the additional info with Android version. Nevermind..

**Comment by yochananmarqos** [comment]
I can't reproduce it now. It's happened in the past, but then I would forget about it since it would stop happening again after an update & reboot. I finally opened an issue because the issue stuck around longer than usual this time. :man_shrugging:

**Comment by yochananmarqos** [comment]
Scratch that. I can reproduce it again. I have no idea why it's intermittent like that.

**Comment by yochananmarqos** [comment]
The issue has popped up again. Could you please install Manjaro GNOME in a VM and test this? 

EDIT: Redacted unneeded sentence.

**Comment by atrashler** [comment]
> The issue has popped up again. Could you please install Manjaro GNOME in a VM and test this? I'll be cancelling my subscription, looking for another program and abandoning the AUR package (I'm the maintainer) if this continues.

The version of the app?

**Comment by yochananmarqos** [comment]
I'm using 7.2.17 (desktop) and 7.2.22 (Android).

**Comment by yochananmarqos** [comment]
Maybe an option to ignore files could be added?  I think what's happening may be the file is being copied to the clipboard, but then ClipTo converts that into the path being copied to the clipboard. Therefore, I can no longer paste the copied file.

**Comment by atrashler** [comment]
> Maybe an option to ignore files could be added? I think what's happening may be the file is being copied to the clipboard, but then ClipTo converts that into the path being copied to the clipboard. Therefore, I can no longer paste the copied file.

Actually, the app should skip any binary data in the clipboard. By the current logic, the app only listens for text changes in the clipboard. And the listening for changes is implemented as 'clipboard long-polling'. So it should not block or break any other app. That is why I need to check it more deeply on the specific platforms:)

**Comment by yochananmarqos** [comment]
It turns out ClipTo is not to blame. I had not realized I still had clipboard monitoring enabled with [Join](https://joaoapps.com/join/) this whole time and it was conflicting..
