### ISSUE TITLE
Issue with auto-sync on Android

### ISSUE THREAD

**Issue by Benko111** [clipto-pro/Desktop#123]
Hi there,
sometimes (as just now) I got the problem of my desktop version not syncing changes I made to my Android (for instance, adding a link). Even after playing around for ten minutes, adding new notes etc that particular note on Android is not updated. Any possibility to start syncro manually? Couldn't find anything like that. Otherwise just great tool. Thanks for answering.

Ben

**Comment by atrashler** [comment]
> Hi there, sometimes (as just now) I got the problem of my desktop version not syncing changes I made to my Android (for instance, adding a link). Even after playing around for ten minutes, adding new notes etc that particular note on Android is not updated. Any possibility to start syncro manually? Couldn't find anything like that. Otherwise just great tool. Thanks for answering.
> 
> Ben

Could you write the version of the Desktop and Mobile apps?

**Comment by Benko111** [comment]
Sure, sry I forgot.

Desktop: 7.2.6
Android on Galaxy S10: 7.1.14

Problem still persists, whichever note I edit, after saving or even closing and opening app again it just won't sync. Never had that behaviour before. It seems I'm above my rate limit, but I checked and haven't even used half of it.

**Comment by atrashler** [comment]
> Sure, sry I forgot.
> 
> Desktop: 7.2.6 Android on Galaxy S10: 7.1.14
> 
> Problem still persists, whichever note I edit, after saving or even closing and opening app again it just won't sync. Never had that behaviour before. It seems I'm above my rate limit, but I checked and haven't even used half of it.

**If you sign out the app on Android and sign in it again:**
1) will you see the same number of notes as on Desktop
2) will you see any new changes instantly

**If you sign in on your mobile, but via browser editor (https://clipto.pro/#/editor):**
1) will you see the same number of notes as on Desktop
2) will you see any new changes made on Desktop instantly (and vice versa)

**Comment by atrashler** [comment]
Please respond if the problem is actual in the upcoming release v7.2.7
