### ISSUE TITLE
Notes loosing tags once copied

### ISSUE THREAD

**Issue by kevinchan169** [clipto-pro/Desktop#125]
Most of our notes would lose their tags once we copied them. It happens since 1 or 2 days ago.

**Comment by atrashler** [comment]
> Most of our notes would lose their tags once we copied them. It happens since 1 or 2 days ago.

1) Install the latest version from Google Play
2) Go to Settings -> Astral Sync
3) Sign out the app and sign in again or click on “Rebuild data index” button

The same can be achieved by sign out and sign in on Desktop.

Let me know if it helped or not. Probably I need to upgrade the migration script on server side. Thanks!

**Comment by atrashler** [comment]
Closed due to no response. Actually, the problem should be solved by sign out and sign in again (the app need to rebuild its local index due to internal changes and specific on some platforms).
