### ISSUE TITLE
mishandled duplicates - clips with the exact same text are not saved

### ISSUE THREAD

**Issue by roamerhappiness** [clipto-pro/Desktop#14]
### (hold ctrl to open in new tab)
<a href="https://youtu.be/yrs2wM6YqvE" target="_blank">![GIF Clipto Pro Issue 1 - mishandled duplicates](https://user-images.githubusercontent.com/55665696/65392891-01daa180-dd48-11e9-9055-5af03adfcb21.gif)

**Comment by atrashler** [comment]
In the latest release (2.2.2) the next logic is applied for such cases:

If you create a note (B) and a note with the same text is already exists (A) then the app will update the note A by following the algorithm:
1) if note B has a title then it will be applied to note A;
2) if note B has tags then note A will be fulfilled with this tags;
3) if note B has files then note A will be fulfilled with this files;
