### ISSUE TITLE
settings icon bug - when the window is maximized the settings icon is slightly hidden

### ISSUE THREAD

**Issue by roamerhappiness** [clipto-pro/Desktop#15]
When using the desktop application, and the window is maximized, the settings gear icon is slightly hidden.

[https://youtu.be/1O60njpXhNM](https://youtu.be/1O60njpXhNM)

(hold ctrl to open in new tab)

<a href="https://youtu.be/1O60njpXhNM">![GIF Clipto Pro Issue 3 - settings icon bug](https://user-images.githubusercontent.com/55665696/65396411-cfdf3480-dd73-11e9-9a47-e3672a9069dd.gif)</a>

**Comment by atrashler** [comment]
v.1.3.0

**Comment by roamerhappiness** [comment]
installed the new version and this bug is gone :)
