### ISSUE TITLE
settings scrolling bug - when viewing the settings applet, the scroll bar grows continuously and you start to lose access to the bottom of the settings

### ISSUE THREAD

**Issue by roamerhappiness** [clipto-pro/Desktop#16]
When I click the settings gear icon on the desktop application, the settings applet window scroll bar starts to grow in size and grows continuously, and meanwhile the bottom of the applet window slowly starts to become less and less accessible until you are unable to see the bottom portion of the settings applet.

[https://youtu.be/pjLZE_YNF6g](https://youtu.be/pjLZE_YNF6g)

(hold ctrl to open in new tab)

<a href="https://youtu.be/pjLZE_YNF6g">![GIF Clipto Pro Issue 4 - settings scrolling bug](https://user-images.githubusercontent.com/55665696/65397131-7549d680-dd7b-11e9-8b38-a97bb4f89131.gif)</a>

**Comment by atrashler** [comment]
v1.3.0

**Comment by roamerhappiness** [comment]
installed the new version and this bug is gone too :)

**Comment by atrashler** [comment]
Thanks for the issue:)
