### ISSUE TITLE
secondary quick interface

### ISSUE THREAD

**Issue by roamerhappiness** [clipto-pro/Desktop#18]
It would be nice to have a secondary interface that is more efficient with faster functionality and less clicks. I would add an option to the list that appears when you right-click the taskbar icon. The new option would appear below "track clipboard" and would be checkable like two options that are currently there. The new option would be "quick interface". When this option is activated it would change the function of the left-click. Currently when you left-click the taskbar icon it opens the standard Clipto interface. This new option would change the left-click action so that it opens a "quick interface" which would be a smaller window at the bottom right of the screen which just lists the clips without all the other icons or options in the standard interface. When clicking the clips on this quick interface, the clip would copy and paste, all at once, with one click, instead of just copying like the standard interface. I would also allow clips to be highlighted using the keyboard up and down arrows and allow switching between tags with the keyboard left and right arrows. I would also allow clips to be selected using both the mouse click and the keyboard enter key.

I am not sure, but this may be similar to what atrashler was trying to accomplish with his suggestion here:
[https://github.com/clipto-pro/Desktop/issues/8](https://github.com/clipto-pro/Desktop/issues/8)

[https://youtu.be/K2Uws66HdoA](https://youtu.be/K2Uws66HdoA)

(hold ctrl to open in new tab)

<a href="https://youtu.be/K2Uws66HdoA">![gif](https://user-images.githubusercontent.com/55665696/65824682-ed604280-e23a-11e9-9e2c-e7c50ce8e123.gif)</a>

**Comment by atrashler** [comment]
questions:

1) have you tried to resize the app? because it switches the interface based on the size of the window and remembers the last size of the window after re-open the app
2) have you tried to configure hotkeys (the setting is available starting from version 1.3.0). So you can configure 'enter' to copy or change navigation keys for your choice.

**Comment by roamerhappiness** [comment]
I didn't realize you could resize it like that! That is awesome! It's just like what I was suggesting. :)

I don't see anything about the hotkeys though. Where do I find the hotkey stuff?

**Comment by atrashler** [comment]
Below the label 'Shortcut Keys':) The setting is available starting from version 1.3.0

<img width="707" alt="image" src="https://user-images.githubusercontent.com/20585947/65836749-ab96d100-e2fa-11e9-85ab-f00304e0cd47.png">

**Comment by roamerhappiness** [comment]
I see them now. I don't see any keys that will copy and paste in one click. Maybe you could make the keyboard enter key have that function?

I do see how you can hold ctrl+up or ctrl+down to cycle the tags. Would it be possible to make the left and right arrow keys do the same thing?

**Comment by atrashler** [comment]
> I don't see any keys that will copy and paste in one click. Maybe you could make the keyboard enter key have that function?

Yes. Now it is possible to only assign 'enter' key for 'Copy' action but not paste. It can simplify the process of Copy/Paste by using the combination of 'Enter' key for Copy and 'Hide on copy' setting. But paste to fields in other apps is not implemented yet (have such request and need more time for investigation).



> I do see how you can hold ctrl+up or ctrl+down to cycle the tags. Would it be possible to make the left and right arrow keys do the same thing?

Yes. You can click on an item and define your own shortcut key(s).

**Comment by roamerhappiness** [comment]
That is so awesome!! :)
