### ISSUE TITLE
version 1.4.0 installed. The software asks me to update to 1.3.0.

### ISSUE THREAD

**Issue by franco27** [clipto-pro/Desktop#19]
Hello

Windows 10 x64 - 1.4.0 Clipto

1/ I installed Clipto v1.4.0 (updated version 1.3.0)
2/ at startup, the software informs me that I am not at the latest version and offers me to download v1.3.0
3/ apparently the user data has been deleted because I had to re-enter my login details (to activate my account and be able to synchronize) +
also my settings have been lost: select again the language, theme, ...

**Comment by atrashler** [comment]
Please do not use the version 1.4.0:)
It is not officially released yet and published with WIP status for test purposes.
The latest official release is 1.3.0
The next incremental update will not have such problems.
Sorry for inconvenience with build 1.4.0

**Comment by franco27** [comment]
Yes, I know it wasn't a final version.

I wanted to help you look for bugs by using it.

**Comment by atrashler** [comment]
Thanks! We should make some kind of Beta channel in Google Play for this purpose.
Still do not know how to do it. Probably create a separate project on Github with Beta builds...

**Comment by franco27** [comment]
Here is the bug for the desktop version

yes it would be a good idea to be able to install Beta or unfinished versions to help you report bugs
- for both versions : Android and Desktop.
But by keeping the final version installed (as Opera, Edge, Chrome,...)
(that the Beta version does not replace the installation of the final version)

Thank you
