### ISSUE TITLE
be able to select multiple copies or notes for action of a task.

### ISSUE THREAD

**Issue by franco27** [clipto-pro/Desktop#20]
Windows 10 x64 -  v1.3.0 

I would have liked to be able to select several notes at the same time to merge, delete,...
like in android version.

**Comment by atrashler** [comment]
duplicate of #7

**Comment by franco27** [comment]
Yes, indeed this suggestion is complementary to the other.

**Comment by atrashler** [comment]
fixed in v2.1.0
