### ISSUE TITLE
[Feature Request] Monochrome tray icon (Linux)

### ISSUE THREAD

**Issue by yochananmarqos** [clipto-pro/Desktop#22]
The Clipto Pro icon looks a bit out of place, don't you think?
![Screenshot from 2019-10-16 15-15-49](https://user-images.githubusercontent.com/5437803/66959582-e8b3d080-f027-11e9-9344-74344b7f37e5.png)

`clipto.pro-bin` 1.4.4-1 (AUR)
Manjaro GNOME

**Comment by atrashler** [comment]
Will check it

**Comment by atrashler** [comment]
> The Clipto Pro icon looks a bit out of place, don't you think?
> ![Screenshot from 2019-10-16 15-15-49](https://user-images.githubusercontent.com/5437803/66959582-e8b3d080-f027-11e9-9344-74344b7f37e5.png)
> 
> `clipto.pro-bin` 1.4.4-1 (AUR)
> Manjaro GNOME

please check it in the latest update v1.7.3

**Comment by yochananmarqos** [comment]
Thank you, it is indeed an improvement. However, the outline could be a little thicker.
![Screenshot from 2019-12-01 18-37-49](https://user-images.githubusercontent.com/5437803/69924845-9826f400-146a-11ea-96bd-70d2dd114880.png)

Just curious: What's with the seemingly random, non-standard icon sizes; i.e., 
* 30 - ?
* 44 - ?
* 71 - ?
* 89 -?
* 107 - ?
* 142 - ?
* 150 - ?
* 284 - ?
* 310 - ?

**Comment by atrashler** [comment]
Will check it:)

**Comment by yochananmarqos** [comment]
Well, the icon is larger and looks a little nicer in v1.8.1. The outline is still thin, but because it's larger it makes up for it a bit. Thanks for the update!

**Comment by atrashler** [comment]
> Well, the icon is larger and looks a little nicer in v1.8.1. The outline is still thin, but because it's larger it makes up for it a bit. Thanks for the update!

Hi!
We use open-source icon for the project and can not modify it (only resize). If someday we change the icon to something more good looking, we will make it more thick.
Thanks for the feedback!
