### ISSUE TITLE
No note created in Win10 after copying a text (but I can paste it and see it on the Android app)

### ISSUE THREAD

**Issue by skaldk** [clipto-pro/Desktop#24]
It's a bit weird and I'm still wondering if it's related to a mistake on my side or something wrong between apps. Just to let you know.

Here is the thing : 

I can copy any text from anywhere on Win10, I can see it in the CliptoPro app on Android and paste it anywhere on both devices.
But when I open the Win10 app... the text doesn't appears at all in the note list (no note created).

In short : the clipboard syncs perfectly, but the text doesn't show up on the Win10 app

Any clue ?

(FYI I checked settings on both sides... I found nothing that could be an obvious mistake on my side)

**Comment by atrashler** [comment]
1) Check that a filter is not applied on Windows to filter by some criteria that do not match your new notes.
2) Check that the amount of notes is the same on all platforms. If it is not the try to re-login on the platform where the data is less actual.
3) If it is possible and the previous recommendations do not work please send us a screenshot or a video how it looks like, probably we miss something..

**Comment by atrashler** [comment]
Hi!
Have you solved the problem?

**Comment by skaldk** [comment]
Hi! 
I just came to check if I had any replies so now I can check that. 

Ok for the 3.
Will give you some feedback anyway. 

Thx

**Comment by skaldk** [comment]
Yup,
Logoff/logon solved the problem, you ain't miss anything 👍 

I also updated the app, but I logoff/logon before updating just to check your guesses and that was the right solution.

Seriously the best multi-device clipboard ever tried (and I tried a lot).
