### ISSUE TITLE
new tags are not added to the search area

### ISSUE THREAD

**Issue by aisbergde** [clipto-pro/Desktop#25]
when I assign new tags then they are listed on the left but they are not added to the search area. I need to quit clipto-pro, and they will be listed.

feature request: new tags should be added to the search area when they are added and used.

Cliptopro 1.4.4 Windows

**Comment by atrashler** [comment]
Will check it. It should work as you described. Thanks!

**Comment by atrashler** [comment]
fixed in v2.1.0
