### ISSUE TITLE
Notes auto-delete (enhancement)

### ISSUE THREAD

**Issue by skaldk** [clipto-pro/Desktop#31]
Add a features to automatically delete notes after a while (hours, days, week) except the favorites

Since a lot of notes are created from the clipboard and some sensitive data eventually ends there (password, bank account, your mum's new phone number,...), regular deletion seems a good practice.

**Comment by atrashler** [comment]
> Add a features to automatically delete notes after a while (hours, days, week) except the favorites
> 
> Since a lot of notes are created from the clipboard and some sensitive data eventually ends there (password, bank account, your mum's new phone number,...), regular deletion seems a good practice.

Yes. It will be added. Thanks!

**Comment by atrashler** [comment]
But it is still not implemented. I am working on it now:)

**Comment by skaldk** [comment]
Yes I know !

But You replied accordingly to my question. Just need to wait a bit ;)

**Comment by atrashler** [comment]
fixed in v2.8.1
