### ISSUE TITLE
multiselect items and add tags

### ISSUE THREAD

**Issue by aisbergde** [clipto-pro/Desktop#33]
I can't find an easy way to multi select items and tag them. The only way I see is to edit each item separately and add tags.
The only way I found is to use the universal clipboard, to bring items to android and to tag them in the android app.

**Comment by atrashler** [comment]
> I can't find an easy way to multi select items and tag them. The only way I see is to edit each item separately and add tags.
> The only way I found is to use the universal clipboard, to bring items to android and to tag them in the android app.

This functionality will be added to the Desktop apps also. If you find some feature on Android it means that it will be implemented in Desktop apps also:)

**Comment by atrashler** [comment]
fixed in v2.1.0
