### ISSUE TITLE
Feature Request: Quick actions in Notification

### ISSUE THREAD

**Issue by anjanoleti** [clipto-pro/Desktop#34]
It would be really handy to have a few quick actions like 'share', 'open link', etc. in the notification itself. Otherwise, everytime it is needed to open the app to perform routine tasks.

**Comment by atrashler** [comment]
> It would be really handy to have a few quick actions like 'share', 'open link', etc. in the notification itself. Otherwise, everytime it is needed to open the app to perform routine tasks.

We have such plans to add one more 'Notification Style' with the behaviour like in the app 'Clipboard Actions'. Thanks!

**Comment by anjanoleti** [comment]
Awesome.. I was using that app and removed it when I installed Clipto. Was missing that function. Great news!

**Comment by atrashler** [comment]
Could you please check this functionality in the latest app release (2.42.12)
It should work. The new notification style is 'Clipboard Actions'

**Comment by anjanoleti** [comment]
It is working great, but with one important option missing.. "SHARE"
Thanks!

**Comment by atrashler** [comment]
The list of available actions is based on the actions that are defined (and checked) from the note’s details screen (right bottom ‘three dot’ action in note screen). It has Share and many other actions. You can activate and make available in notification up to 16 actions.

Please check it. Thanks!

**Comment by anjanoleti** [comment]
Sorry, had missed that.. nice to choose the actions :)
Request one addition to the Clipboard Actions notification. The ability to 'PASTE' from system clipboard to Clipto.
