### ISSUE TITLE
Notification theme

### ISSUE THREAD

**Issue by anjanoleti** [clipto-pro/Desktop#35]
Only the default notification gets themed according to the changes in system wide theme. But the control themes remain white even if I apply dark theme to the phone. It would be nice to see it changed.

**Comment by atrashler** [comment]
Could you send a screenshot please, app version and the information about your device (Android version, Device name, etc)?
Thanks!

**Comment by anjanoleti** [comment]
App version: 2.35.13-release (2351300)
Device name: Samsung Galaxy Note 10 Plus
Model number: SM-N975F
Software version: One UI with Android 10


![Screenshot_20191224-175631_Total Launcher](https://user-images.githubusercontent.com/59110401/71413166-f2386500-2676-11ea-82e5-8cfe1741cb67.jpg)
![Screenshot_20191224-175644_Total Launcher](https://user-images.githubusercontent.com/59110401/71413180-fd8b9080-2676-11ea-84f6-fad83bb05cdc.jpg)

**Comment by atrashler** [comment]
> App version: 2.35.13-release (2351300)
> Device name: Samsung Galaxy Note 10 Plus
> Model number: SM-N975F
> Software version: One UI with Android 10
> 
> ![Screenshot_20191224-175631_Total Launcher](https://user-images.githubusercontent.com/59110401/71413166-f2386500-2676-11ea-82e5-8cfe1741cb67.jpg)
> ![Screenshot_20191224-175644_Total Launcher](https://user-images.githubusercontent.com/59110401/71413180-fd8b9080-2676-11ea-84f6-fad83bb05cdc.jpg)

Have reproduced it. It seems like a known issue of Samsung One UI for all custom notifications (https://developer.samsung.com/forum/board/thread/view.do?boardName=SDK&messageId=366355&startId=00lIU~&startPage=7&curPage=9).

We can try to solve it by using the color theme of the application but it will have not the same color as all other system notifications

**Comment by anjanoleti** [comment]
Oh alright.. thanks

**Comment by atrashler** [comment]
> Oh alright.. thanks

Have reopened it due to found possibility to make some kind of hotfix for this problem)

**Comment by atrashler** [comment]
> Oh alright.. thanks

Could you check the latest version? I have applied the logic: "notification color theme = app theme". So if you set dark theme in the app then the same color theme will be applied for all custom notifications. The color can be slightly different then the notification panel but will definitely identify that this notification of Clipto:)

**Comment by anjanoleti** [comment]
Yes, it works as you've mentioned. Thanks a ton for attending to it.
May I request you to add a complete "black" theme to the app, in addition to the current dark theme? Because that is a popular system theme and the theme I use as well :)

**Comment by atrashler** [comment]
> Yes, it works as you've mentioned. Thanks a ton for attending to it.
> May I request you to add a complete "black" theme to the app, in addition to the current dark theme? Because that is a popular system theme and the theme I use as well :)

What about AMOLED Black? It is fully black (#000)

**Comment by anjanoleti** [comment]
Oops.... thanks!
I had tried it earlier, but the notification colour did not change. Did not know that I had to restart the app for changes to reflect in Notification. Got it now :)

**Comment by atrashler** [comment]
restart is not necessary. Notification need to be updated (with a new clip or by switch off/on ‘Notes from Clipboard’). But you are right, I need to fix it also. The concept of the app: to apply changes instantly without any additional steps)

**Comment by atrashler** [comment]
The notification style is depends on applied theme of the app. So it should look correctly on all devices now.
