### ISSUE TITLE
Getting notification about the `new clip` on sender device

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#36]
I have 3 devices:
<kbd>A</kbd> <kbd>B</kbd> <kbd>C</kbd>
If I copy from device <kbd>A</kbd> other two devices (<kbd>B</kbd> & <kbd>C</kbd>) should get notified about the `new clip`. Right?
Sender device (<kbd>A</kbd>) should not get notified. But every time I copy something, oftentimes it's giving me a notification about this `new clip`.

To understand what I meant [Watch Here](https://streamable.com/56ckd)

**Comment by atrashler** [comment]
> I have 3 devices:
> A B C
> If I copy from device A other two devices (B & C) should get notified about the `new clip`. Right?
> Sender device (A) should not get notified. But every time I copy something, oftentimes it's giving me a notification about this `new clip`.
> 
> To understand what I meant [Watch Here](https://streamable.com/56ckd)

Yes. It should not work in such way. Will check it. Thanks!

**Comment by atrashler** [comment]
Hi!
Could you check if it is still actual in the latest release 2.7.2?

**Comment by tahsinature** [comment]
nope... because I use it almost every hour. so I know

**Comment by atrashler** [comment]
> nope... because I use it almost every hour. so I know

Ok. Thanks!

**Comment by atrashler** [comment]
> nope... because I use it almost every hour. so I know

Could you please write your devices info (for each of them):

1) platform
2) version of the app
3) is 'Notes from Clipboard' activated
4) is 'Universal Clipboard' activated

I need it to reproduce the issue. Thanks!

**Comment by atrashler** [comment]
Still can not reproduce it. I have two Android devices and one Desktop.
Every time I copy something on any of this devices I get notified only on two others.

Could you please answer on previous questions and (if it is possible) attach a video how it looks (the previous video is not available)?

**Comment by tahsinature** [comment]
I'm not having this issue anymore.

**Comment by tahsinature** [comment]
fixed
