### ISSUE TITLE
Clipto Pro not working, also after reinstall

### ISSUE THREAD

**Issue by christiandull** [clipto-pro/Desktop#38]
Clipto Pro is not working correct. Clips are at 0 and not saved. The login also not working (it returns after i put my E-Mail and passwort, but still see "Sign In").

Reinstall don't help.

What can i do?

**Comment by christiandull** [comment]
The settings page is empty.

**Comment by atrashler** [comment]
Could you send the additional details:
1) the app version that you are trying to install
2) the desktop platform and its version (Windows/Linux/OSX)
3) the country where you are trying to sign in
4) have you installed the app before and which version

additionally:
1) try to login with the same account on our site and check if the notes are available across site and desktop app.

Waiting for your reply!

**Comment by christiandull** [comment]
1. It first appears after a update (to 1.8.0 i think - before it was working). Now i run 1.8.6. Also when i run the old version 1.7.x it is no more running.
2. I use Windows 10
3. Germany (don't think it is a login problem, because the settings are not showing)
4. See 1.

Additionally:

1. It works on your site, also at my laptop and on my android mobile phone. Only not at my main pc.

I have made a video for you, there you can see what i see (reinstall or install of other versions don't change this):

https://www.dropbox.com/s/rgho8c2v0nsirar/CliptoPro.mp4?dl=0

**Comment by atrashler** [comment]
Could you try to find and remove a folder and try to login again?
The folder should be somewhere here:
C:\Users\<user>\AppData\Roaming\Clipto Pro

**Comment by christiandull** [comment]
I removed the folder and reinstalled the program. Now it works fine. Thanks
