### ISSUE TITLE
Can't get past choose your language pop-up

### ISSUE THREAD

**Issue by RobNeilly** [clipto-pro/Desktop#39]
Hi there,

I just started using your app on Android, but as I wanted multiplatform, I downloaded the Windows version today. I set it up, but cannot move past the Choose your language pop-up. It defaults to English (US), which is correct, but it's stuck here. Choosing another language doesn't move forward either. Thanks for your help. ~Rob

**Comment by atrashler** [comment]
Hi! Yes, I also reproduced it:)
The action “Next” is hidden at the bottom of the popup and you could scroll the popup to the bottom (or resize the app to make its height more)

It will be fixed in the next release.

Thanks!

**Comment by RobNeilly** [comment]
Alex,

That has got to be one of the most super fast replies I've ever received!
And it's a good one. Thanks so much, I think I'm going to really like using
this app everywhere.

Rob

**Comment by atrashler** [comment]
Has it helped to solve the problem? (I mean resizing or scrolling)

**Comment by RobNeilly** [comment]
Alex

I couldn't really scroll, so I tabbed to the button and was able to make it
work.

Rob

**Comment by atrashler** [comment]
OMG, it is really problem. Will solve it asap.

Thanks for letting me know!

**Comment by atrashler** [comment]
fixed in version 2.4.0

**Comment by RobNeilly** [comment]
Thanks, Alex! Great app ☺️

Rob
