### ISSUE TITLE
Bug Report: Clipboard won't sync from Windows PC to Android, only other way around

### ISSUE THREAD

**Issue by Abragus** [clipto-pro/Desktop#40]
I'm able to use Universal sync to copy clipboard from Android to Windows 10 PC, but not the other way around. The copied text shows up in the notes section on both the Android and the PC, but the clipboard does not change. 

I'm running a OnePlus 3T on Android 9.

**Comment by atrashler** [comment]
Could you write the version of the Android app?

**Comment by atrashler** [comment]
> I'm able to use Universal sync to copy clipboard from Android to Windows 10 PC, but not the other way around. The copied text shows up in the notes section on both the Android and the PC, but the clipboard does not change.
> 
> I'm running a OnePlus 3T on Android 9.

Could you also check that the option 'Universal Clipboard' is active on your OnePlus device

**Comment by Abragus** [comment]
@atrashler Universal Clipboard is on on both devices. App version is Clipto Pro 2.41.2-release (2410200)

**Comment by atrashler** [comment]
The problem is only with universal clipboard? The sync functionality works (if you create something or modify)?

**Comment by Abragus** [comment]
@atrashler 

1. I'm guessing you mean if it shows up in the Notes section in the app? It does. 
2. It shows up in the app when I do/change something on the PC. It doesn't seem to show in the notification, though, and the clipboard on the phone does not get updated. 
3. The phone is running Android 9. 

Sorry for answering slowly.

**Comment by atrashler** [comment]
> @atrashler
> 
> 1. I'm guessing you mean if it shows up in the Notes section in the app? It does.
> 2. It shows up in the app when I do/change something on the PC. It doesn't seem to show in the notification, though, and the clipboard on the phone does not get updated.
> 3. The phone is running Android 9.
> 
> Sorry for answering slowly.

Strange. Could you please make one more test (I can not reproduce it on my devices so it requires your help). Here the scenarios:

**[Scenario 1]**
1) On your mobile device apply Sort Order 'Usage Count' in the main list
2) On your mobile device activate 'Universal Clipboard'
3) On your Desktop device copy some note that you can see on your mobile device also

**Expected result:**
1. on your mobile device you see the increased counter of 'Usage Count' attribute of the copied note, the note is highlighted.
2. the note is put into the clipboard of your mobile device


**[Scenario 2]**
1) On your mobile device active notification style 'Clipboard History'
2) On your mobile device kill the app activity from your recents apps (make sure that the notification is still available)
3) On your mobile device copy some note via notification action and check that the note is available in the clipboard
4) On your Desktop device copy some another note and check that the note is placed into the clipboard and the notification is updated with the new information

**Comment by atrashler** [comment]
I have reproduced it!!!:)
Will fix in the next release.
Thanks for letting me know!

**Comment by atrashler** [comment]
Please check the latest version 2.42.6 from beta channel. It should work.
Thanks!

**Comment by Abragus** [comment]
Thanks a lot for the quick answers and solution! It's working great now. Will leave a review on the Play Store!
