### ISSUE TITLE
Clipto occupy the shortcut, please add toggle to the shortcut.

### ISSUE THREAD

**Issue by gth7754125** [clipto-pro/Desktop#41]
clipto has some shortcut conflict with vs-code on my mac.
'cmd + shirt + p' to show all commands on vscode.
please add a toggle function for the clipto shortcut.

**Comment by atrashler** [comment]
In Settings -> Behaviour-> Shortcut Keys you could change this shortcut to something else.

Please check if it works or not on your device.

**Comment by gth7754125** [comment]
> In Settings -> Behaviour-> Shortcut Keys you could change this shortcut to something else.
> 
> Please check if it works or not on your device.

i know, but how could i just set the shortcut nothing ?

**Comment by atrashler** [comment]
Now you can’t. Have not thought about such scenario:) Will add such ability. Thanks!

**Comment by atrashler** [comment]
solved in version 2.4.0
