### ISSUE TITLE
for God sake give the option to disable a certain shortcut

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#43]
there is no way to disable a certain shortcut
if I don't need a shortcut, why I have to assign it to a key. doesn't make any sense.
by default, if I wanna go to command palette on my vscode `ctrl + shift + p`, clipto always catching this. So when I wanted to disable it, OMG there are no options.
![2020-03-06_14-13-35](https://user-images.githubusercontent.com/41298152/76060988-1b4d6e00-5fb5-11ea-91e1-73b8bec1dbe5.png)

**Comment by atrashler** [comment]
The functionality to disable shortcuts will be available in the next release. Thanks!

**Comment by atrashler** [comment]
solved in version 2.4.0
