### ISSUE TITLE
Can't sign in with Google using 2.4.0

### ISSUE THREAD

**Issue by yochananmarqos** [clipto-pro/Desktop#45]
It gets stuck here:

![Screenshot from 2020-03-08 19-58-06](https://user-images.githubusercontent.com/5437803/76176676-42ec3400-6177-11ea-8525-d7394e874e27.png)

It should be offering to use other 2FA methods since security keys don't work with Electron or CEF.

**Comment by atrashler** [comment]
Could you try to sign in to the Desktop app by using the same sign in button but with ‘Shift’ key pressed?

The core engine (firebase) updates its security policy and some issues with it are possible while I am updating the app clients to this changes.

**Comment by atrashler** [comment]
The problem should be solved now. Could you check it again by using the normal flow with 2FA and in-app sign in dialog?

**Comment by yochananmarqos** [comment]
My security key worked this time using the standard flow.
