### ISSUE TITLE
Clipto Pro 2.4.0 fails to install on a fresh machine

### ISSUE THREAD

**Issue by chtof** [clipto-pro/Desktop#46]
Screenshot : https://pasteboard.co/IYnuSbb.png

Clipto Pro 2.4.0 fails to install on a fresh machine (Windows 2012 R2 without any updates).
Does Clipto Pro requires some dependencies to be installed (like .net for example)?
Last know successfull version was 2.2.2.

Thnaks in advance.

**Comment by chtof** [comment]
Does not happened when installed outside Chocolatey package management so should be an issue on the Chocolatey side.

**Comment by atrashler** [comment]
Be aware that I publish the app only on Github and can not guarantee that any other build outside of it is not modified or damaged by third party people.

**Comment by chtof** [comment]
I think remember someone from your team has allowed to embed binaries in a Chocolatey package.
But currently, the Chocolatey package will only download the binary from your download URL during the installation, so it doesn't currently embed your binary.
And regarding the issue, I have to check that but I think version 2.4.0 is no longer compatible with Windows 2012 r2 (contrarilt to the version 2.2.2). In case you have information about that, I am interested.

**Comment by atrashler** [comment]
> @atrashler I think remember someone from your team has allowed to embed binaries in a Chocolatey package.
> But currently, the Chocolatey package will only download the binary from your download URL during the installation, so it doesn't currently embed your binary.
> And regarding the issue, I have to check that but I think version 2.4.0 is no longer compatible with Windows 2012 r2 (contrarilt to the version 2.2.2). In case you have information about that, I am interested.
Yes. I have confirmed that the app can be distributed via Chocolatey. My attention is about general case when the app can be modified and distributed by someone else.  

Will check the problem. The installation package should work on all windows versions starting from Windows 7. However the version 2.2.2 was compiled on Windows machine while 2.4.0 on linux-based server. Will publish the updated release soon(within 8-16 hours) that will be compiled on Windows as before. Probably this is an issue.

Thanks!

**Comment by atrashler** [comment]
Have uploaded new build (https://github.com/clipto-pro/Desktop/releases/tag/v2.4.4). It was compiled on Windows machine and probably should work on a fresh machine (but I am not sure because I do not have a fresh machine:).
