### ISSUE TITLE
Installer does not replace previous version.

### ISSUE THREAD

**Issue by cmarabate** [clipto-pro/Desktop#47]
I downloaded and installed the latest version of clipto when it notified me in the app that there was an update to download. After installing it I noticed that it was not working correctly at all, which is when I noticed that I had 3 version of clipto installed and 2 of them were currently running at the same time.

Every other installer I have ever used would always replace the previous version with the new version.

I always used the default install directory, and when I look inside it looks like there is only one version installed but when I view my installed programs it was showing 3 different versions.

I had already uninstalled one of them before I thought about letting you know about this but here is a screenshot showing that I currently have 2 versions installed...
![image](https://user-images.githubusercontent.com/12236062/76688395-a60c1980-6602-11ea-8ed4-2c2d3d4cf195.png)

I'm going to uninstall all of them and start fresh. I'm guessing that will fix my issue but please make it easier to update to the new versions.

**Comment by atrashler** [comment]
I apologize for inconvenience:)
The latest versions were updated with new internal identifier (I have mentioned it in release notes but did it not obviously). All future versions will have the same identifier now and will not require to uninstall the app (means that it will be updated correctly).
