### ISSUE TITLE
feature request - remove shortcut, not only change the shortcut

### ISSUE THREAD

**Issue by aisbergde** [clipto-pro/Desktop#49]
Currently it is only possible to change the shortcut, but not to remove or to dactivate. I have some issue with clipto-pro grabbing shortcuts which are standard in other programs, for example in Azure data Studio, Visual Code. I don't want to assign another shortcut but it should be possible to delete or to deactivate some specific shortcuts.

**Comment by atrashler** [comment]
It is available in the latest version (2.4.6). 'Clear' action on the attached screenshot.

If you update from any previous version prior 2.4.x please uninstall it before.

Thanks!

<img width="1291" alt="clear_shortcut" src="https://user-images.githubusercontent.com/20585947/77745456-fa13f680-7023-11ea-80e1-c2409686b048.png">

**Comment by atrashler** [comment]
closed due to implemented behaviour
