### ISSUE TITLE
Unable to log in Windows desktop app

### ISSUE THREAD

**Issue by prouland** [clipto-pro/Desktop#50]
Hi,

I encouter some issues on logging in desktop Windows (2.6.6) app.

I firstly tried to log with a Google Account and had this error screen :

![clipto-login1](https://user-images.githubusercontent.com/1228173/78797313-d0f64d00-79b7-11ea-8123-f7b8c40649ab.png)

Then, trying to log in with a mobile number, passing the vérification code, then has a blank log window.

Is there something to do to make it works ?

**Comment by atrashler** [comment]
if you have updated from any previous version prior 2.4.x then:
1) uninstall previous app
2) find this folder and remove it: C:\\Users\{User}\AppData\Roaming\Clipto Pro (or Clipto)
then install the app

if it does not help then try to sign in by clicking the same button “Sign In” but in combination with “Shift”

**Comment by prouland** [comment]
Well thanks !

It was a first time installation, and a previous reinstallation try did not the trick.
But, the sign in from the browser (with Shift) worked like a charm.

Thanks again.

**Comment by atrashler** [comment]
strange. Will make it as a default flow.
The issue was with the latest version 2.6.6?

**Comment by prouland** [comment]
Yes
