### ISSUE TITLE
Unable to toggle Windows desktop app from notification area to taskbar 

### ISSUE THREAD

**Issue by spxt4928** [clipto-pro/Desktop#51]
It seems that the Windows desktop app stays at the notification area (system tray) with a small icon by default.
And there is no way to let it appear on the taskbar with a big icon.
<img width="120" alt="clipto_systray" src="https://user-images.githubusercontent.com/24370957/78935661-c1722380-7adf-11ea-820e-866db3791cd1.png">
I want the app to appear on the taskbar since I use it frequently.
But it stays behind when I switch to other apps.
I have to tap the notification area to find the small icon or minimize all other apps whenever I need it. 
It's kinda annoying.
I can't find a way to toggle the app to move to taskbar with big icon. 
Is there a way to make it always stay on the taskbar with a big icon like other apps installed by default?

**Comment by atrashler** [comment]
It will be fixed in the next release:)

**Comment by spxt4928** [comment]
right, thanks

**Comment by atrashler** [comment]
fixed in 2.7.2
