### ISSUE TITLE
Windows front-end sign-in hangs

### ISSUE THREAD

**Issue by kirk-rs** [clipto-pro/Desktop#52]
Just installed v2.7.2
Found sign-in link (not intuitive; make it more obvious to find!).
Just spins without end, even after patiently waiting after any minutes.
Not clear if my notes from Android mobile device (I've used the app over a year there) will simply populate into my Windows PC (but I'm hopeful, once I've signed in).

**Comment by atrashler** [comment]
Could you check the same sign in flow but click the button while holding ‘Shift’?

**Comment by atrashler** [comment]
> Just installed v2.7.2
> Found sign-in link (not intuitive; make it more obvious to find!).
> Just spins without end, even after patiently waiting after any minutes.
> Not clear if my notes from Android mobile device (I've used the app over a year there) will simply populate into my Windows PC (but I'm hopeful, once I've signed in).

Could you please answer? Also please check our recommendations how to solve problems with authorisation on Desktop - https://clipto.pro/l/f91nrrark2saJahaA

**Comment by atrashler** [comment]
The problem should be solved by following the next flow: https://clipto.pro/l/f91nrrark2saJahaA
