### ISSUE TITLE
not going to background v2.7.2

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#53]
after installing `v2.7.2` if I exit the app, it stays in the dock. If I quit it, it permanently has gone.

<img width="566" alt="Image 2020-04-18 09-09-51" src="https://user-images.githubusercontent.com/41298152/79625630-67fb9b80-8154-11ea-932d-c1aaa139f384.png">

**Comment by atrashler** [comment]
I have added an optional setting 'Show in the task bar' that is enabled by default. To turn it off you can do it from the tray icon and the behaviour will be as before 2.7.2

Or you have found some issue that I do not understand?:)

**Comment by tahsinature** [comment]
done. thanks
