### ISSUE TITLE
No Syncing between devices.

### ISSUE THREAD

**Issue by rpawar0703** [clipto-pro/Desktop#54]
I am using Android 9 device with Clipto 2.44.6 and Windows 10 Pro with Clipto 2.7.9
There is no syncing between either apps.

**Comment by atrashler** [comment]
> I am using Android 9 device with Clipto 2.44.6 and Windows 10 Pro with Clipto 2.7.9
> There is no syncing between either apps.

Hi! There is no problem with server and syncing should work correctly on all devices.
To understand the problem could you please send me the next details:

1) Do you have any restrictions of Google Services in your country
2) Do you have the same network or not for Android and Desktop apps
3) Do you use the same account (strange question but some users create two separate accounts:)
4) Could you sign in into Web version of the app and check if it syncs data with Android or Desktop (https://clipto.pro/#/editor)

**Comment by rpawar0703** [comment]
I was about to delete the issue because now its working OK. I just reinstalled the both apps. Thanks for such a wonderful app.

**Comment by atrashler** [comment]
Great!

If such happen again please let me know. Usually it is not necessarily to re-install the app.
However here the short instruction how to solve authorisation problem on Desktop - https://clipto.pro/l/f91nrrark2saJahaA

Thanks!
