### ISSUE TITLE
Clicking attachment no longer opens details, dims screen instead

### ISSUE THREAD

**Issue by proxycyber** [clipto-pro/Desktop#57]
Clipto: Windows Desktop edition.

When I click the file attachment filename, below note title, it now dims the screen instead of opening the side panel details page of the attachment selected.

**Comment by atrashler** [comment]
Could be an issue of Desktop app. Try to change theme to any of ‘Dark’ and it should temporary solve the issue:)
Have solved it on Web, but Desktop client will be updated in few days.

**Comment by jacoque** [comment]
I have the same issue.
When I change theme to  "OSCURO" "AZUL OSCURO" "DARK BLURPLE" or "NEGRO AMOLED" the app works fine. (I use it in spanish)
With whatever other theme it crash.
Thanks

**Comment by atrashler** [comment]
> I have the same issue.
> When I change theme to "OSCURO" "AZUL OSCURO" "DARK BLURPLE" or "NEGRO AMOLED" the app works fine. (I use it in spanish)
> With whatever other theme it crash.
> Thanks

Yes. Now it works with Dark themes only:) Will be fixed in the next release.

**Comment by jacoque** [comment]
> 
> 
> > I have the same issue.
> > When I change theme to "OSCURO" "AZUL OSCURO" "DARK BLURPLE" or "NEGRO AMOLED" the app works fine. (I use it in spanish)
> > With whatever other theme it crash.
> > Thanks
> 
> Yes. Now it works with Dark themes only:) Will be fixed in the next release.

No problem, dark theme or light theme is almost the same.
For me the most importan thing is that the sync is "instantanea" it doesn't take time for to see the files in the others computers.
Thanks, good job

**Comment by atrashler** [comment]
fixed in v2.8.1
