### ISSUE TITLE
v2.7.9 linux data not syncing 

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#58]
I tried quite a few times. Uninstalled and downloaded from both GitHub releases and official site. Same issue. It's happening from this version. The previous version was working fine.

![Screenshot from 2020-04-29 09-19-04](https://user-images.githubusercontent.com/41298152/80555493-9bfb7a00-89fa-11ea-9b5e-f3a05b7bf67a.png)

**Comment by atrashler** [comment]
1) could you write the previous app version?
2) could you check that even after the steps in the next article it does not work (or works?) - https://clipto.pro/l/f91nrrark2saJahaA
