### ISSUE TITLE
different browsers showing different data at the same time

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#59]
we expect all the browsers to show the same data at the same time. as those data are in the browser and from our account directly.
the screenshot is after refreshing those browsers so many times.
![clipto diff data](https://user-images.githubusercontent.com/41298152/81037790-1e3ddf80-8ece-11ea-88d2-319e3e59a41e.png)

**Comment by atrashler** [comment]
Could you try to sign out of the app in all of your browsers and sign in again?

Seems like an issue with some internal changes in the Web and Desktop apps and incorrectly indexed local cache.

**Comment by atrashler** [comment]
closed due to upgraded web app and the problem related to it
