### ISSUE TITLE
all the notes duplicated

### ISSUE THREAD

**Issue by tahsinature** [clipto-pro/Desktop#60]
LoL. out of nowhere, I am seeing my all notes became duplicated. so what now? should I have to manually filter all of my 7000 notes one by one? or remove all the data?
ridiculous.
![clipto dup prob](https://user-images.githubusercontent.com/41298152/81039411-23515d80-8ed3-11ea-9fd6-697089040300.png)

**Comment by atrashler** [comment]
Have you tried to sign out the app and sign in again? Seems like the problem with local index.

**Comment by tahsinature** [comment]
nope. should I sign out?
signing in again with social Auth, it's cumbersome

**Comment by atrashler** [comment]
> nope. should I sign out?
> signing in again with social Auth, it's cumbersome

Yes. Please try it. I have just added this issue to the backlog so I do not have any alternative solution of it.

**Comment by atrashler** [comment]
Have found why it is happening. Probably you have signed in on Web and then signed in on Desktop by using the same browser to complete the authorisation flow.
At least I have reproduced my scenario and will check how to solve it:)
Thanks!

**Comment by atrashler** [comment]
Have updated the Web version. The problem was specific to a browser and did not spread notes across devices
