### ISSUE TITLE
Remove keyboard shortcut

### ISSUE THREAD

**Issue by rpawar0703** [clipto-pro/Desktop#62]
I'm using version 2.7.9 on windows 10. There is a keyboard shortcut (Ctrl+Shift+P) associated with the clipto which I did not assign. How to remove it, there is no option to remove it in the settings?

**Comment by atrashler** [comment]
Go to Settings -> Shortcut Keys -> Find a shortcut that you want to delete or change -> Click on it -> Click on 'Clear' action or create a new combination.

Will make it more user friendly later:)

**Comment by rpawar0703** [comment]
Sorry I didn't look for this setting. Problem solved. Thnaks
