### ISSUE TITLE
How to undo deleting?

### ISSUE THREAD

**Issue by Mark-Joy** [clipto-pro/Desktop#63]
I accidentally deleted one big fat note and failed to press undo button in time when it appeared. Where can I find the undo button? Is there "Recycle Bin" in desktop version?
Is there anything i can do to restore the note?

**Comment by atrashler** [comment]
Recycle Bin will be added in the Desktop version in the next release (approximately within 3-5 days).
Now if you have deleted something on a Desktop, there is no way to restore it (the app does not save your data data in the cloud if you have deleted it).

**Comment by Mark-Joy** [comment]
Sounds good. Thanks for your hard work! Clipto is the best app across platform regarding quickly noting and saving.

**Comment by atrashler** [comment]
> Sounds good. Thanks for your hard work! Clipto is the best app across platform regarding quickly noting and saving.

Have updated the Web version of the app (please check it, but re-login first - http://clipto.pro). Desktop clients will also be updated soon.

**Comment by atrashler** [comment]
recycle bin is added in v2.8.1
