### ISSUE TITLE
App is not opening

### ISSUE THREAD

**Issue by rpawar0703** [clipto-pro/Desktop#67]
I'm using app version 2.7.9
When I updated to version 2.8.1 and tried to open the app, app didn't opened. I even tried to open it as administrator.
I'm using Windows 10 Build 19645.mn_release.200605-1502. It's an insider edition.

**Comment by atrashler** [comment]
try to do the following: https://clipto.pro/l/f91nrrark2saJahaA
But it will remove all local cache on the Desktop.

And to understand the problem, could you tell if you have any software that could clean/remove temporary data of other apps?

**Comment by rpawar0703** [comment]
Still, not opening.
I don't use any software to clean/remove temporary data.

**Comment by atrashler** [comment]
1) Does it write you any error on screen?
2) Does it display an icon in a taskbar?
3) Have you tried to re-install the app?
4) Does the installation process complete successfully?

**Comment by atrashler** [comment]
Probably the issue is because of this:) - https://github.com/electron/electron/pull/24039

Will update the build in 1-2 days (working on some security update so need some time). Anyway you could use previous version until I publish the new one. Thanks for letting me know.

**Comment by rpawar0703** [comment]
1. No error screen.
2. No taskbar icon.
3. Re-installed app many times.
4. Installation process completed successfully.

Using version 2.7.9 unit next update. Working fine.

Thanks for quick replies.
