### ISSUE TITLE
File attaching not working.

### ISSUE THREAD

**Issue by SoPat712** [clipto-pro/Desktop#68]
I add a file to a note on my phone, and it doesn't appear on my computer. Could you link this app to google drive in some way, and it just spits out our own google drive link so we can just download things easier?

**Comment by atrashler** [comment]
Could you check and write me:
1) does your phone display you that the file is uploaded (the attachment on the note’s screen colored in green or has a thumbnail)
2) could you send me a screenshot or write how the icon of the attachment looks like on your computer for the same note

**Comment by SoPat712** [comment]
Attached: 
![image](https://user-images.githubusercontent.com/30350506/84941296-2ed99c00-b0af-11ea-92e1-40a7e1b3ea08.png)
Desktop view of clips. There is no tag for attachment, and the clipboard item is not even there.

Phone View next:
![image](https://user-images.githubusercontent.com/30350506/84941352-431d9900-b0af-11ea-9714-0cb0b968bf42.png)
![image](https://user-images.githubusercontent.com/30350506/84941373-4d3f9780-b0af-11ea-8aa5-b3fa35876cff.png)
![image](https://user-images.githubusercontent.com/30350506/84941380-516bb500-b0af-11ea-84a5-5478a0b7dd01.png)


If you need anything else, then just ask me.

**Comment by atrashler** [comment]
1) On your phone the note seems like it was uploaded (it is good:)
2) On the computer I can see that the whole note has not appeared. Right?

Could you send me the version of the Android version? Also it will be
useful if you check:
1) does the note created on Android is appeared on your Desktop
2) does the note created on your Desktop is appeared on your Android device
3) authorize in the browser and check the same scenario in pair with
Android and Desktop.

In all three cases we expect that your notes are synced instantly across
all your devices. There should not be any delay.

Waiting for your reply.

**Comment by SoPat712** [comment]
It just uploaded at 1:58 PM apparently. Sending screenshots again.

Desktop upload

![image](https://user-images.githubusercontent.com/30350506/84954209-f3e16380-b0c2-11ea-9208-9ac6aaac944c.png)

I did another test 2, and it's broken. It seems it takes like 3 hours to sync or something?

![image](https://user-images.githubusercontent.com/30350506/84954413-563a6400-b0c3-11ea-882b-ee991f29310b.png)

Phone upload 2
![image](https://user-images.githubusercontent.com/30350506/84954444-66eada00-b0c3-11ea-935e-fafb4db86bd7.png)

Not sure what the problem here is.

Android Version right here

![image](https://user-images.githubusercontent.com/30350506/84954498-82ee7b80-b0c3-11ea-8b96-e060bb058801.png)


Thanks for all your help so far.

**Comment by SoPat712** [comment]
I think I might have the solution. Do you by any chance require googlesyndication.com for the app?

**Comment by SoPat712** [comment]
This is a big misunderstanding. I use a PiHole on my network, and I have a large blocklist I use that breaks google functionality sometimes. It seems as though someone on my network blocked googleapis.com and googlesyndication.com.

I just had to whitelist those, and I'm extremely sorry for wasting your time.

**Comment by atrashler** [comment]
The app uses Cloud Firestore that is hosted on firebaseio.com. I do not
know how it resolves all routing so I can not suggest what what the cause
of the problem.
The normal behaviour of the app is to sync data no more than 1-2 seconds
between all devices. If it is not true then something has happened:)
