### ISSUE TITLE
Clipto freezes my computer after Windows 2004 Update

### ISSUE THREAD

**Issue by christiandull** [clipto-pro/Desktop#69]
Hello,

after the Windows 2004 update my computer freezez maybe 15 seconds after starting. Then i need to push the reset button on my computer. It took me 1-2 hours to find out that clipto cause the freeze. 

I deactivated it from autostart. But when i open manually clipto, the computer freeze 1-2 seconds later.

What i tried, but not helped:

Install the newest version of clipto (2.8.1)
Reinstall the programm
Delete the entire folder "C:\Users\%USERNAME%\AppData\Roaming\Clipto

Don't know what to do and why it freezez the completly computer.

**Comment by atrashler** [comment]
Seems like because of this issue - https://github.com/electron/electron/pull/24039
Will recompile the app in 1-2 days. Thanks for letting me know.

**Comment by atrashler** [comment]
Could you check the latest version? It should be fixed there. https://github.com/clipto-pro/Desktop/releases/tag/v3.1.0
