### ISSUE TITLE
Question about Sync limits

### ISSUE THREAD

**Issue by rpawar0703** [clipto-pro/Desktop#70]
sync limits are monthly or lifetime?

**Comment by atrashler** [comment]
sync limit is applied to the number of notes.
For example, if you have no more than 300 notes and have 10 devices, than all if them can be synced and you will not see the difference. But if you have exceed the limit and created 301 notes, then this new note will not be synced until you delete any other note. And no matter if you exceed the limit or not - any existing note will by synced if you update its content.
Do not know if I answered the question or not, but let me know so I can add some more details:)

**Comment by atrashler** [comment]
By the way, you could also join my 'closed testing program' and get enough limit to organise thousands of your notes after I successfully apply the new technical solution to reduce the costs of instant sync.
Here the link with more details if you are interesting - https://clipto.pro/l/w3fBt9Cx9S4ECEXC6

**Comment by rpawar0703** [comment]
I've sent the email. Thanks.

**Comment by atrashler** [comment]
Please update to the latest release versions:
https://github.com/clipto-pro/Desktop/releases/tag/v3.1.0
https://github.com/clipto-pro/Android/releases/tag/v3.2.0
