### ISSUE TITLE
Linux - Appimage not showing app name in title bar of window

### ISSUE THREAD

**Issue by inkstain** [clipto-pro/Desktop#73]
All other Appimage apps I am running will update the title bar on launch to correspond with the app name, but Clipto does not. In my case it just shows 'VMapp command' which seems to suggest it is pulling a null data field from somewhere.

I am running appimage ver 2.9.1 on a Fedora 32 VM on Qubes-OS. (it showed the same issue when I was running Fedora 30 earlier today).

Please let me know if you have any questions or need additional info

thx!

**Comment by atrashler** [comment]
In this version it should be solved (https://github.com/clipto-pro/Desktop/releases/tag/v3.0.7). But be aware that this version create notes in a new internal format that requires to use all our apps of the same major version 3.x

**Comment by inkstain** [comment]
Confirmed fixed in 3.0.7 (thanks for the headsup on the need to upgrade Android as well).

For your support notes: the fix did not take effect until I nuked the local config (~/.config/Clipto) folder which of course required relogging in, but all went well (aside from flash notice indicating upgrade was available to 2.9.1 :) )

Thx!

**Comment by atrashler** [comment]
> Confirmed fixed in 3.0.7 (thanks for the headsup on the need to upgrade Android as well).
> 
> For your support notes: the fix did not take effect until I nuked the local config (~/.config/Clipto) folder which of course required relogging in, but all went well (aside from flash notice indicating upgrade was available to 2.9.1 :) )
> 
> Thx!

This is a pre-release:) When it become a release, this banner will not be shown (it will happen in few hours).
Android version 3.x is here (or will be available in Beta channel of Google Play in few hours) - https://github.com/clipto-pro/Android/releases/tag/v3.1.8

**Comment by atrashler** [comment]
Please update to the latest version (3.2.1) on Google Play and follow the procedure of optimization that will revert the previously made changes if you have already run this procedure. Thanks!
