### ISSUE TITLE
Need ability to disable or change Keyboard Shortcuts

### ISSUE THREAD

**Issue by inkstain** [clipto-pro/Desktop#75]
Need to be able to change or disable keyboard shortcuts. For instance, `Ctrl+Sh+P` is used by Sublime Text and other tools to open up a command palette so I would have to close Clipto often so it won't interfere.

thx!

**Comment by atrashler** [comment]
Now it is possible to clear or change any shortcut in settings. Will make it more understandable later. But now it is possible to do via Settings > Shortcut Keys
