### ISSUE TITLE
There is no option to sort Notes as in Android version

### ISSUE THREAD

**Issue by Mark-Joy** [clipto-pro/Desktop#76]
As title, currently there is no option to sort Notes as in Android version
Thank you.

**Comment by atrashler** [comment]
In Desktop version sort options are available:
1) if you click on “three dots” for the specific category in the left navigation
2) if you click on “notes counter at the right of the search bar in the main list”. In this case the sort options will be applied to the current filtered list either it is filtered by one tag or by any other combination of tags

**Comment by Mark-Joy** [comment]
ohhh Thank you!! I got it
