### ISSUE TITLE
Is there any way to permanently delete a label?

### ISSUE THREAD

**Issue by hotigris** [clipto-pro/Desktop#77]
I can't find the option to delete a label from label list.
Thank you!

**Comment by atrashler** [comment]
> I can't find the option to delete a label from label list.
> Thank you!

Sure. If a label does not have any notes, you could see a 'Delete' action at the right top corner on the tag's settings popup.

**Comment by hotigris** [comment]
Thank you very much, Alex. But I can't see anything at the right top corner
– if the tag's settings popup is what is seen on the attached picture.
Imre

**Comment by atrashler** [comment]
Did not get your attachment:) Here the video - https://clipto.pro/l/Sgn8pdd8aA3Gzzhu6

**Comment by hotigris** [comment]
Thank you for the video. So now I have to reformulate my problem: I can't
see the whole tag's settings popup, or... maybe the name of the label is
too long and it hides the delete icon. Is there a possibility to edit the
label name? :)
Well I will try to attach the picture again.
[image: 2020-07-09_214841.jpg]
Imre

**Comment by atrashler** [comment]
The issue with a long tag will be fixed in the next release (have reproduced it and on my computer it is possible to scroll this panel to see the right corner).
Rename option will be added later.
Thanks!
By the way, you have not attached a screenshot:) Never mind.

**Comment by hotigris** [comment]
Thank you. (I attached the screenshot in both of my letters, the problem
must be elsewhere, I don't understand.)
Imre
