### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by its-just-yo** [clipto-pro/Desktop#78]
I have 300 notes plan, and it's not syncing any notes because I am over the limit, but wouldn't it make sense to sync starred and most recent notes upto 300 and leave the rest as local?

**Comment by atrashler** [comment]
What do you mean 'leave the rest as local'? To 'unsync' some old notes? It could lead to unpredictable results when you will lost some data. Now you can fully control what you sync or not by the following ways
1) disable automatic sync in the account's settings. After that you can sync any note(s) which you prefer, but manually.
2) if you do not care about some oldest notes then probably you are using the functionality 'notes from the clipboard', aren't you? If so, you can limit this category up to the free limit and get fully functional cross-platform clipboard manager that will automatically remove the eldest clips with the newest once the limit of 'notes from clipboard' is reached.

**Comment by its-just-yo** [comment]
It sounds like what you are saying is that I cannot use the local clipboard to search through my thousands of snippets as needed because the app does not know how to handle syncing the latest 300 only. Is my understanding correct ?

**Comment by atrashler** [comment]
> It sounds like what you are saying is that I cannot use the local clipboard to search through my thousands of snippets as needed because the app does not know how to handle syncing the latest 300 only. Is my understanding correct ?

No. The app does not care about any offline activity. If you are using the app as a clipboard manager, it does not limit your activity on a device at all and the app can be used as a fully functional notes & clipboard manager.

The synchronisation limit only affects will your local notes be stored in the cloud and available across all your devices or not.

For example: you have 4 devices and want to have the same clipboard across all of them. If you have <=300 notes then the app syncs all your notes as it was before and you have absolutely the same notes across all your devices. If you create a new note 301, it will not be synced and will be available only on the device where you have created it. If you reduce your notes back to 300 (delete some existing notes, for example) - all created new will be synced and become available across all devices.

So the app is fully functional offline and let to search, delete, merge and do any existing (and future) operations with no restrictions. The restrictions are only applied on the functionality of cloud sync.
