### ISSUE TITLE
Focus on title - at every edit not just when creating a note

### ISSUE THREAD

**Issue by lauriond** [clipto-pro/Desktop#80]
version:  3.4.5, browser (Chrome 85.x.x.x); does not apply to Android (I have to manually focus by tapping)

The setting `Focus on title when creating a note` is ON.

1. When creating a new note it is working as expected.

2. When editing an existing note:
_Expected Result_: start editing the note body.
_Actual Result_: as with new note, the focus is in the title of the note.

**Comment by atrashler** [comment]
Will check it. Seems like an issue. Very good explanation of the issue (with actual and expected blocks), thanks!!!

**Comment by atrashler** [comment]
fixed in v4.0.0 (coming soon)
