### ISSUE TITLE
Wrong national flag for chinese traditional 

### ISSUE THREAD

**Issue by Yusei-StarDust** [clipto-pro/Desktop#82]
Please correct to the right flag, or just remove flag icon to avoid any argument

**Comment by atrashler** [comment]
> Please correct to the right flag, or just remove flag icon to avoid any argument

Here the problem with it. Windows Store does not let to publish the app on it if it has the right flag. As a hotfix I have put a wrong flag, but yes, it need to be set as blank or some abbreviation. Still do not know what to use here.

**Comment by Yusei-StarDust** [comment]
> Here the problem with it. Windows Store does not let to publish the app on it if it has the right flag. As a hotfix I have put a wrong flag, but yes, it need to be set as blank or some abbreviation. Still do not know what to use here.

But in .exe version,  it also has this problem. This is not involved in Windows Store policy.

**Comment by atrashler** [comment]
Will use an emoji code '🇹🇼'. The rendering should be the part of the platform. Lets see how Windows will display it and will it be possible to use it, because technically the app does not use any special resource for it:)

**Comment by atrashler** [comment]
fixed in 4.5.5
