### ISSUE TITLE
请问是中国人开发的吗？

### ISSUE THREAD

**Issue by hotsymbol** [clipto-pro/Desktop#83]
上传的数据会加密吗？？你会不会后台偷看？

**Comment by atrashler** [comment]
Now the app uses:

1) transport layer encryption (https)
2) server-side encryption (https://cloud.google.com/firestore/docs/server-side-encryption)

It will also suppory end-to-end encryption, but later. Requires to investigate it more deeply to make it useful.

**Comment by atrashler** [comment]
closed due to anwered question (not an issue)
