### ISSUE TITLE
обновлять когда версию для десктопа?

### ISSUE THREAD

**Issue by g0blin-NN** [clipto-pro/Desktop#85]
я на нашем. великом и могучем. ничего? на великом можно два тома войны и мир написать. на могучем пересказать в двух словах. :)
для андроид версия далеко вперед ушла. и по функциям и по номеру. для компьютеров сильно отстает.
недостатки по картинкам.
анимированный webp не показывает. от слова совсем. с прозрачностью webp показывает. но все картинки не вписывает в окно. а маленькие зачем-то увеличивает. да и не плохо бы указывать размер картинок.
![Буфер обмена01](https://user-images.githubusercontent.com/66860852/97123660-e22d5e00-173d-11eb-98af-12a1ce530ae6.png)
на этой картинке видим анимацию файла 2685523.webp. вернее вообще ничего не видим. и она не передалась на андроид.
![Буфер обмена02](https://user-images.githubusercontent.com/66860852/97123743-3afcf680-173e-11eb-9067-1dec06d5c059.png)
на этой видим как 45x30  зачем-то увеличили и даже больше окна.
![Буфер обмена03](https://user-images.githubusercontent.com/66860852/97123857-c9717800-173e-11eb-8f9e-b1370a80a684.png)
на этой размером 674x1000 прозрачность есть. но лис не уместился в область просмотра.
![Буфер обмена04](https://user-images.githubusercontent.com/66860852/97124192-2a4d8000-1740-11eb-8d32-315219b460d7.png)
тут картинка 1366x854 не показана целиком.
![Буфер обмена05](https://user-images.githubusercontent.com/66860852/97124305-9cbe6000-1740-11eb-96f0-abf53a290fac.png)
а тут jpeg прекрасно вписался. размер 450x450

на андроид все эти картинки видны в нормальных миниатюрах т.е. вписаны целиком. кроме первой конечно.

**Comment by atrashler** [comment]
В настоящий момент занимаюсь этим (на самом деле, версия сайта обновляется, а десктоп компилируется  в итоге из той же кодовой базы что и сайт). То есть, ближайший релиз будет по десктопу (не по андройду). 

Можете в виде публичных ссылок поделиться примером на заметку с кривым отображением webp? (мне так будет существенно легче проверить исправление до и после).

Спасибо!

**Comment by g0blin-NN** [comment]
странно. сегодня анимация заработала. а вот с масштабированием неполадки.
https://clipto.pro/l/cRBK5mkzydMQa3ky9
ссылка
а на андроид анимацию webp не показывает. gif показывает.

**Comment by atrashler** [comment]
Да, с масштабированием что-то не задалось (поправлю). На андройд webp тоже посмотрю.
Ссылку пока не закрывайте на пример:)

**Comment by g0blin-NN** [comment]
> Ссылку пока не закрывайте на пример:)
там счетчик тикает.

**Comment by atrashler** [comment]
> Ссылку пока не закрывайте на пример:)
> там счетчик тикает.

проверьте плиз, я обновил сайт.

**Comment by g0blin-NN** [comment]
теперь вроде нормально. только вот мелкие изображения, которые вписываются в окно просмотра, может не стоит увеличивать? а показывать как есть? просто уменьшать большие до окна просмотра и все. все остальное 100% размера показывать. 
и не плохо бы показывать размер, ну в смысле в пикселях. 45x30...
что-то типа этого....
![Clipto_-_2020-10-31_06 28 30](https://user-images.githubusercontent.com/66860852/97770281-e04f0a80-1b42-11eb-8a4c-e9bc4925004a.png)
из меня конечно тот еще художник :)

**Comment by g0blin-NN** [comment]
ну бум считать картинки поправились.

**Comment by atrashler** [comment]
не, там еще превью не сделано и метаданные не показываются. Пока просто не знаю как это сделать (в основном полноэкранные превьюшки)

**Comment by g0blin-NN** [comment]
на счет webp, есть утилита которая рассказывает все о картинке. [webpinfo](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-windows-x64.zip) лежит в архиве с кодеком. все утилиты для терминала. cli короче. исходники [тут](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz). в общем все версии [тут](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html). остальное [mediainfo](https://mediaarea.net/ru/MediaInfo) наверно знает. mediainfo у webp точно размеры(или как правильнее разрешение?) не понимает. а gif, jpeg, png понимает. проверял.
