### ISSUE TITLE
Attached file not present

### ISSUE THREAD

**Issue by NolanNolan** [clipto-pro/Desktop#87]
hi
i created a new note and attached a pdf on my laptop. OPening Clipto on my phone and stationary PC showed the note and a circle with an arrow, but clicking it did not open the pdf - nothing happened

I tried it again and this time saw a link pointing at a place on my disk - but clicking it opened microsoft store asking to download some app (the attachment is a standard pdf)

any idea ?

regards Nolan
![Clipboard Image](https://user-images.githubusercontent.com/30736282/101241953-cdf45d80-36fa-11eb-8411-874289eca953.jpg)

**Comment by atrashler** [comment]
The icon “arrow up” indicates that the file is not uploaded and the uploading is in progress. Could you try to open the app on device where you have initiated the uploading and wait until the process is completed (usually you should see the progress immediatly, but if it does not happen, please try to attach the file again).
On test devices it works correctly, but probably you have found some issue that need to be checked:)

**Comment by NolanNolan** [comment]
I just tested, it never finishes upload

What could be the reason ?

Strange, on reboot the settings and login was deleted from the app  had to setup again

nolan


Fra: Alex Trashler <notifications@github.com>
Sendt: 5. december 2020 16:33
Til: clipto-pro/Desktop <Desktop@noreply.github.com>
Cc: Jørn Bue Madsen <Nolan@myletter.dk>; Author <author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


The icon “arrow up” indicates that the file is not uploaded and the uploading is in progress. Could you try to open the app on device where you have initiated the uploading and wait until the process is completed (usually you should see the progress immediatly, but if it does not happen, please try to attach the file again).
On test devices it works correctly, but probably you have found some issue that need to be checked:)

**Comment by NolanNolan** [comment]
Clicking or double clicking a attachment does not open the file (when using Windows app) is that intended ?

Thanks
nolan


Hilsen Jørn

From: Jørn Bue Madsen<mailto:Nolan@myletter.dk>
Sent: 5. december 2020 16:45
To: clipto-pro/Desktop<mailto:reply@reply.github.com>
Subject: SV: [clipto-pro/Desktop] Attached file not present (#87)

I just tested, it never finishes upload

What could be the reason ?

Strange, on reboot the settings and login was deleted from the app  had to setup again

nolan


Fra: Alex Trashler <notifications@github.com>
Sendt: 5. december 2020 16:33
Til: clipto-pro/Desktop <Desktop@noreply.github.com>
Cc: Jørn Bue Madsen <Nolan@myletter.dk>; Author <author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


The icon “arrow up” indicates that the file is not uploaded and the uploading is in progress. Could you try to open the app on device where you have initiated the uploading and wait until the process is completed (usually you should see the progress immediatly, but if it does not happen, please try to attach the file again).
On test devices it works correctly, but probably you have found some issue that need to be checked:)

**Comment by NolanNolan** [comment]
found the culprit regarding upload: Kaspersky,  now solved

thanks
Hilsen Jørn

Fra: Jørn Bue Madsen<mailto:Nolan@myletter.dk>
Sendt: 5. december 2020 16:51
Til: clipto-pro/Desktop<mailto:reply@reply.github.com>
Emne: RE: [clipto-pro/Desktop] Attached file not present (#87)

Clicking or double clicking a attachment does not open the file (when using Windows app) is that intended ?

Thanks
nolan


Hilsen Jørn

From: Jørn Bue Madsen<mailto:Nolan@myletter.dk>
Sent: 5. december 2020 16:45
To: clipto-pro/Desktop<mailto:reply@reply.github.com>
Subject: SV: [clipto-pro/Desktop] Attached file not present (#87)

I just tested, it never finishes upload

What could be the reason ?

Strange, on reboot the settings and login was deleted from the app  had to setup again

nolan


Fra: Alex Trashler <notifications@github.com>
Sendt: 5. december 2020 16:33
Til: clipto-pro/Desktop <Desktop@noreply.github.com>
Cc: Jørn Bue Madsen <Nolan@myletter.dk>; Author <author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


The icon “arrow up” indicates that the file is not uploaded and the uploading is in progress. Could you try to open the app on device where you have initiated the uploading and wait until the process is completed (usually you should see the progress immediatly, but if it does not happen, please try to attach the file again).
On test devices it works correctly, but probably you have found some issue that need to be checked:)

**Comment by atrashler** [comment]
The reason could be that the app can not complete the uploading due to wrong authorization or problems with the internet.
If the authorization was reseted after reboot, probably the local app cache was damaged (have you run any cleaner that can remove or modify application cache?).
Please try to login again and upload the file again. Let me know the result of it. Thanks!

**Comment by NolanNolan** [comment]
HI again

found the culprit regarding blocked upload: it was Kaspersky internet security blocking,  I removed the entrance and reinserted it its now solved. Thanks

regards Nolan




Fra: Alex Trashler <notifications@github.com>
Sendt: 5. december 2020 17:49
Til: clipto-pro/Desktop <Desktop@noreply.github.com>
Cc: Jørn Bue Madsen <Nolan@myletter.dk>; Author <author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


The reason could be that the app can not complete the uploading due to wrong authorization or problems with the internet.
If the authorization was reseted after reboot, probably the local app cache was damaged (have you run any cleaner that can remove or modify application cache?).
Please try to login again and upload the file again. Let me know the result of it. Thanks!

**Comment by NolanNolan** [comment]
But is it intentional that clicking a link to an attached file eg a text or pdf file opens a suggestion to microsoft store see screenshot attached ? I would have assumed that the file opened in the normal windows registered app and double clicking the file did the same


Fra: Jørn Bue Madsen
Sendt: 6. december 2020 11:49
Til: clipto-pro/Desktop <reply@reply.github.com>
Emne: SV: [clipto-pro/Desktop] Attached file not present (#87)

HI again

found the culprit regarding blocked upload: it was Kaspersky internet security blocking,  I removed the entrance and reinserted it its now solved. Thanks

regards Nolan




Fra: Alex Trashler <notifications@github.com<mailto:notifications@github.com>>
Sendt: 5. december 2020 17:49
Til: clipto-pro/Desktop <Desktop@noreply.github.com<mailto:Desktop@noreply.github.com>>
Cc: Jørn Bue Madsen <Nolan@myletter.dk<mailto:Nolan@myletter.dk>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


The reason could be that the app can not complete the uploading due to wrong authorization or problems with the internet.
If the authorization was reseted after reboot, probably the local app cache was damaged (have you run any cleaner that can remove or modify application cache?).
Please try to login again and upload the file again. Let me know the result of it. Thanks!

**Comment by NolanNolan** [comment]
Hi
I downloaded from MS app store but the app don’t start on reboot

Any idea ?
Thanks
Nolan

**Comment by atrashler** [comment]
It should work in the latest version from MS app store (4.5.5). If it does not work, please use the latest version from Github (4.7.0). The version from MS store uses different way to boot the app on the system startup and could have an issue. But version from Github should work correctly:)

**Comment by NolanNolan** [comment]
Thanks
I DL from GitHub that worked. But you will upload latest versino also on MS store ? If the exe files are identical i dont understand why they would behave different why is that ?


Hilsen Jørn

Fra: Alex Trashler<mailto:notifications@github.com>
Sendt: 27. december 2020 15:51
Til: clipto-pro/Desktop<mailto:Desktop@noreply.github.com>
Cc: Jørn Bue Madsen<mailto:Nolan@myletter.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


It should work in the latest version from MS app store (4.5.5). If it does not work, please use the latest version from Github (4.7.0). The version from MS store uses different way to boot the app on the system startup and could have an issue. But version from Github should work correctly:)

**Comment by atrashler** [comment]
EXE and APPX file formats have different boot configuration on Windows and require to be developed separately. For EXE file format I have solved this problem, but for APPX seems like still not. Codebase is the same, but implementation is different.

**Comment by NolanNolan** [comment]
Ok thanks 😊


Hilsen Jørn

Fra: Alex Trashler<mailto:notifications@github.com>
Sendt: 27. december 2020 18:38
Til: clipto-pro/Desktop<mailto:Desktop@noreply.github.com>
Cc: Jørn Bue Madsen<mailto:Nolan@myletter.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [clipto-pro/Desktop] Attached file not present (#87)


EXE and APPX file formats have different boot configuration on Windows and require to be developed separately. For EXE file format I have solved this problem, but for APPX seems like still not. Codebase is the same, but implementation is different.

**Comment by atrashler** [comment]
fixed in v7.2.7
