### ISSUE TITLE
Overflow notes are not deleted even with setting enabled

### ISSUE THREAD

**Issue by Abragus** [clipto-pro/Desktop#88]
Old notes are not getting deleted, even though the setting to do so is enabled. This stops syncing between devices, as it seems I've reached the 300 notes limit, even though it's supposed to delete notes when I have more than 200. 

This only applies to one of my computers, my phone and my laptop are syncing fine (and notes from these devices also show up on the affected computer.) 

Program 4.5.5. 

![image](https://user-images.githubusercontent.com/43346912/102241605-71aeec00-3ef9-11eb-92d1-a3e99e74683b.png)

![image](https://user-images.githubusercontent.com/43346912/102241744-960ac880-3ef9-11eb-88f5-1b13036939dd.png)

This is also kind of similar to a problem I had earlier: https://github.com/clipto-pro/Desktop/issues/40

**Comment by atrashler** [comment]
should be fixed in 7.2.0
