### ISSUE TITLE
Enhancement: Windows PC Hotkey / Shortcuts

### ISSUE THREAD

**Issue by christiandull** [clipto-pro/Desktop#9]
In the past i used ditto. 

There it was able to open the list of the clipboard with a shortcut (in this case, maybe open the program or you can create also a list from where you can insert).

It was also possible to insert the clipboard as plain text with a shortcut (leave the clipboard untouched).

Please add these 2 shortcuts (and maybe more) with the setting to edit these shortcuts.

**Comment by atrashler** [comment]
> In the past i used ditto.
> 
> There it was able to open the list of the clipboard with a shortcut (in this case, maybe open the program or you can create also a list from where you can insert).
> 
> It was also possible to insert the clipboard as plain text with a shortcut (leave the clipboard untouched).
> 
> Please add these 2 shortcuts (and maybe more) with the setting to edit these shortcuts.
> 
> When you add these shortcuts the program/app is perfect for me and i will make a donation to get the lifetime license.

Here the answers and questions:

1) _Now it is possible to show/hide the app by using a shortcut 'Ctrl+Shift+E'._
**Is it not the same? Please clarify your request if you ask something other.**

2) **Do you mean the next scenario?**
     - user opens some app where he need to fill some inputs
     - user place some of the inputs in focus
     - user opens Clipto and click on some note
     - the note is placed into the input
    If so we have such plans to implement it

3) Yes, shortcut keys will be configured via Settings.

P.S.: Your requests are very good and functional and we are waiting for your reply but please do not write in this issue tracker anything else that has nothing to do with the quality of the app - we are not working because of the donations and our goal is different:)

**Comment by christiandull** [comment]
To 1:

Yes, 'Ctrl+Shift+E' is the one thing i asked for, but i use that combination for other tasks. Would be great if i can change it to another hotkey.

To 2:

For my second request, it is possible to do that at the moment with some more steps.

1. Copy some formated text (from Internet or from Word)
2. Press Ctrl+Shift+E
3. Click on the clip button of the newest entry (this will convert the clipboard into plain text)
4. Insert with Ctrl+V (formatting is lost)

But this method is too long and i lose the formatting. With the "new" hotkey it should be:

1. Copy some formated text (from Internet or from Word)
2. Press hotkey (in Ditto i use Ctrl+Shift+V) to insert plain text (keep the formatting in the clipboard)

**Comment by atrashler** [comment]
1. Yes. It will be possible in the next functional release (1.3.0)

2. Thanks for the clarification. We will investigate this issue.

**Comment by christiandull** [comment]
I have tested it with ditto and another program "PureText". 

Both could send the clipboard in plain text. But both converts the clipboard permanently to plain text after using the hotkey to paste.

To reach that in your Program, you need to put Step 2-4 of my description into one hotkey (past latest clip as plain text).

**Comment by atrashler** [comment]
added support of shortcuts - v1.3.0
