### ISSUE TITLE
License and Sync Issues

### ISSUE THREAD

**Issue by XINGUSA1** [clipto-pro/Desktop#94]
I had an early version of Clipto Pro with License. It seems that doesn't anymore.
 I upgraded to a new version of Clipto, non-pro Since it apparently does not exist anymore, and some of my Devices don't log to the same unlimited Clips how can we fix this between my five devices??

**Comment by atrashler** [comment]
Just send me your account id in Clipto. I will check it. It should work if you are using the same account.

**Comment by atrashler** [comment]
Please send me your account id to solve the issue if it still exists. Thanks!
