### ISSUE TITLE
[Bug] Cause soft keyboard close when Clipto is setting clipboard on android

### ISSUE THREAD

**Issue by mmqmzk** [clipto-pro/Desktop#95]
My phone is Oneplus 7T Pro, Hydrogen OS, Android 11, keyboard is Gboard.
When I focus an input field and open Gboard, then copy something on another device, Clipto sync in background, set the clipboard, and flush a text toast, the Gboard close. Sometimes the Gboard will reopen again (may because the input field regain focus), sometimes not. I tried some other keyboards such as Baidu IME, SwiftKey, all of them behave the same.
The Join app from [Joaomgcd](https://joaoapps.com/join/) can do the same thing (sync and set clipboard from background, flush a toast) without closing soft keyboard. Unfortunately, the Join app is deeply depending on GCM, that's why I'm not using it.

Please prevent soft keyboard from close when setting clipboard.

**Comment by atrashler** [comment]
fixed in the latest release on Google Play (5.5.8)
