### ISSUE TITLE
Clipto Desktop search is slow

### ISSUE THREAD

**Issue by sirius16** [clipto-pro/Desktop#97]
I don't know if this is just a problem with me or if my computer is too full and slow but Clipto Pro is very slow on computer. It's blazing fast on my phone but the desktop client is very very slow. I am referring to the search function in particular, it takes a rather long time for Clipto to get the search results I want, which significantly cuts down on its utility in the moment.

**Comment by atrashler** [comment]
> I don't know if this is just a problem with me or if my computer is too full and slow but Clipto Pro is very slow on computer. It's blazing fast on my phone but the desktop client is very very slow. I am referring to the search function in particular, it takes a rather long time for Clipto to get the search results I want, which significantly cuts down on its utility in the moment.

could you please write:
1) the version of the app
2) the number of notes in the list before you start searching
3) the number of notes in the list after you search it by text
4) does the text you are searching by contains commas
5) the platform

**Comment by sirius16** [comment]
Sorry for the delayed response, this was buried in my inbox

1. 4.3.0
2. 19997
3. 2~500 (depending on search)
4. no
5. Windows 10

**Comment by atrashler** [comment]
> Sorry for the delayed response, this was buried in my inbox
> 
> 1. 4.3.0
> 2. 19997
> 3. 2~500 (depending on search)
> 4. no
> 5. Windows 10

Could you check it in the latest version of the app (5.0.3) and send me the same statistics?

**Comment by sirius16** [comment]
1. 5.3.0
2. 19997
3. 2~500 (depending on search)
4. no
5. Windows 10

Search is somewhat faster but still takes around 6-10 secs for
something my phone typically does in less than 3

**Comment by atrashler** [comment]
> 1. 5.3.0 2. 19997 3. 2~500 (depending on search) 4. no 5. Windows 10 Search is somewhat faster but still takes around 6-10 secs for something my phone typically does in less than 3
> […](#)

could you check the latest version 7.2.6 ?

**Comment by sirius16** [comment]
Wait 7.2.6? How many updates have their been? How did i miss 6 entirely?

**Comment by atrashler** [comment]
> Wait 7.2.6? How many updates have their been? How did i miss 6 entirely?

Sorry for the delay. Have not seen this update. It was only one update. I am just aligning the functionality and versioning with the mobile versions. So it can jump in numbers:)

The new version will be available soon. You should see a banner in the app when update is become available.
