### ISSUE TITLE
cannot empty recycle bin

### ISSUE THREAD

**Issue by jackycms** [clipto-pro/Desktop#98]
version 5.0.3 bug :  cannot empty recycle bin,  must re-open the application

**Comment by atrashler** [comment]
thanks! I will check it in the upcoming release.

**Comment by klorinczi** [comment]
I was able to reproduce the bug in Clipto v5.0.3,

Recycle bin is emptied, but the count number is not updated.
Just click to Recycle bin, you will see it is empty.

**Comment by atrashler** [comment]
> I was able to reproduce the bug in Clipto v5.0.3,
> 
> Recycle bin is emptied, but the count number is not updated.
> Just click to Recycle bin, you will see it is empty.

It should be fixed in the release 5.1.0. It is available for download from Github, but is not officially released yet.

**Comment by atrashler** [comment]
please check it in v5.1.1
