### ISSUE TITLE
Clipboard on PC doesnt work

### ISSUE THREAD

**Issue by Krustak** [clipto-pro/Desktop#99]
Hello,

Im new to clipto, still in testing phase. It seems to work really well
but today something strange was happening

On PC (Windows 10 20H2) my clipboard stopped working. CTRL + C doesnt create note in clipto. I had to disable "notes from clipboard" or kill the app to fix this. How can i send you logs or how can we try to find the core of the problem ?

**Comment by atrashler** [comment]
> Hello,
> 
> Im new to clipto, still in testing phase. It seems to work really well
> but today something strange was happening
> 
> On PC (Windows 10 20H2) my clipboard stopped working. CTRL + C doesnt create note in clipto. I had to disable "notes from clipboard" or kill the app to fix this. How can i send you logs or how can we try to find the core of the problem ?

I will check this issue. Probably I have implemented something wrongly. 

No need to send logs for now (I will revise the code first)

Thanks for letting me know!

**Comment by Krustak** [comment]
Hello, today again, clipboard stops working, like CTRL+C does not copy highlighted text, disabled "notes from clipboard" and voila it works again

**Comment by atrashler** [comment]
> Hello, today again, clipboard stops working, like CTRL+C does not copy highlighted text, disabled "notes from clipboard" and voila it works again

Could you install this version and check if it works or not on your platform? If it will not work or will work differently please let me know before I release it officially.

https://github.com/clipto-pro/Desktop/releases/tag/v5.1.0

**Comment by Krustak** [comment]
> > Hello, today again, clipboard stops working, like CTRL+C does not copy highlighted text, disabled "notes from clipboard" and voila it works again
> 
> Could you install this version and check if it works or not on your platform? If it will not work or will work differently please let me know before I release it officially.
> 
> https://github.com/clipto-pro/Desktop/releases/tag/v5.1.0

Hi, thank you.

Before I do anything, I just found out that clipboard from PC can be paired up with Samsung phone via "My phone" app. And as Im forgetting everything I have used this app in past and then stopped, bud did not uninstalled it. 

Is it possible that this app is in conflict with Clipto ?

thank you

**Comment by atrashler** [comment]
> > > Hello, today again, clipboard stops working, like CTRL+C does not copy highlighted text, disabled "notes from clipboard" and voila it works again
> > 
> > 
> > Could you install this version and check if it works or not on your platform? If it will not work or will work differently please let me know before I release it officially.
> > https://github.com/clipto-pro/Desktop/releases/tag/v5.1.0
> 
> Hi, thank you.
> 
> Before I do anything, I just found out that clipboard from PC can be paired up with Samsung phone via "My phone" app. And as Im forgetting everything I have used this app in past and then stopped, bud did not uninstalled it.
> 
> Is it possible that this app is in conflict with Clipto ?
> 
> thank you

I do not know:-) Need to check it.
